#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ABP_F_OldCloth001_Implimentation

#include "Basic.hpp"

#include "ABP_F_OldCloth001_Implimentation_classes.hpp"
#include "ABP_F_OldCloth001_Implimentation_parameters.hpp"


namespace SDK
{

// Function ABP_F_OldCloth001_Implimentation.ABP_F_OldCloth001_Implimentation_C.ExecuteUbergraph_ABP_F_OldCloth001_Implimentation
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UABP_F_OldCloth001_Implimentation_C::ExecuteUbergraph_ABP_F_OldCloth001_Implimentation(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_F_OldCloth001_Implimentation_C", "ExecuteUbergraph_ABP_F_OldCloth001_Implimentation");

	Params::ABP_F_OldCloth001_Implimentation_C_ExecuteUbergraph_ABP_F_OldCloth001_Implimentation Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ABP_F_OldCloth001_Implimentation.ABP_F_OldCloth001_Implimentation_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_F_OldCloth001_Implimentation_AnimGraphNode_KawaiiPhysics_DB22254C408B73DD7E9BC4A62D018730
// (BlueprintEvent)

void UABP_F_OldCloth001_Implimentation_C::EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_F_OldCloth001_Implimentation_AnimGraphNode_KawaiiPhysics_DB22254C408B73DD7E9BC4A62D018730()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_F_OldCloth001_Implimentation_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_F_OldCloth001_Implimentation_AnimGraphNode_KawaiiPhysics_DB22254C408B73DD7E9BC4A62D018730");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_F_OldCloth001_Implimentation.ABP_F_OldCloth001_Implimentation_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_F_OldCloth001_Implimentation_AnimGraphNode_KawaiiPhysics_A8F9A51E4CAB94A2E9F5F58E6AE9E9C8
// (BlueprintEvent)

void UABP_F_OldCloth001_Implimentation_C::EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_F_OldCloth001_Implimentation_AnimGraphNode_KawaiiPhysics_A8F9A51E4CAB94A2E9F5F58E6AE9E9C8()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_F_OldCloth001_Implimentation_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_F_OldCloth001_Implimentation_AnimGraphNode_KawaiiPhysics_A8F9A51E4CAB94A2E9F5F58E6AE9E9C8");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_F_OldCloth001_Implimentation.ABP_F_OldCloth001_Implimentation_C.ClothLayer
// (HasOutParams, BlueprintCallable)
// Parameters:
// struct FPoseLink                        InPose                                                 (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
// struct FPoseLink                        Param_ClothLayer                                       (Parm, OutParm, NoDestructor)

void UABP_F_OldCloth001_Implimentation_C::ClothLayer(const struct FPoseLink& InPose, struct FPoseLink* Param_ClothLayer)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_F_OldCloth001_Implimentation_C", "ClothLayer");

	Params::ABP_F_OldCloth001_Implimentation_C_ClothLayer Parms{};

	Parms.InPose = std::move(InPose);

	UObject::ProcessEvent(Func, &Parms);

	if (Param_ClothLayer != nullptr)
		*Param_ClothLayer = std::move(Parms.Param_ClothLayer);
}


// Function ABP_F_OldCloth001_Implimentation.ABP_F_OldCloth001_Implimentation_C.AnimGraph
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FPoseLink                        Param_AnimGraph                                        (Parm, OutParm, NoDestructor)

void UABP_F_OldCloth001_Implimentation_C::AnimGraph(struct FPoseLink* Param_AnimGraph)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_F_OldCloth001_Implimentation_C", "AnimGraph");

	Params::ABP_F_OldCloth001_Implimentation_C_AnimGraph Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Param_AnimGraph != nullptr)
		*Param_AnimGraph = std::move(Parms.Param_AnimGraph);
}

}

