#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ABP_ElecPanda_Implementation

#include "Basic.hpp"

#include "ABP_ElecPanda_Implementation_classes.hpp"
#include "ABP_ElecPanda_Implementation_parameters.hpp"


namespace SDK
{

// Function ABP_ElecPanda_Implementation.ABP_ElecPanda_Implementation_C.UpperOverride
// (HasOutParams, BlueprintCallable)
// Parameters:
// struct FPoseLink                        NativePose                                             (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
// struct FPoseLink                        ActionPose                                             (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
// struct FPoseLink                        Param_UpperOverride                                    (Parm, OutParm, NoDestructor)

void UABP_ElecPanda_Implementation_C::UpperOverride(const struct FPoseLink& NativePose, const struct FPoseLink& ActionPose, struct FPoseLink* Param_UpperOverride)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_ElecPanda_Implementation_C", "UpperOverride");

	Params::ABP_ElecPanda_Implementation_C_UpperOverride Parms{};

	Parms.NativePose = std::move(NativePose);
	Parms.ActionPose = std::move(ActionPose);

	UObject::ProcessEvent(Func, &Parms);

	if (Param_UpperOverride != nullptr)
		*Param_UpperOverride = std::move(Parms.Param_UpperOverride);
}


// Function ABP_ElecPanda_Implementation.ABP_ElecPanda_Implementation_C.LookAtOverride
// (HasOutParams, BlueprintCallable)
// Parameters:
// struct FPoseLink                        InPose                                                 (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
// struct FVector                          Param_LookAtWorldLocation                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FPoseLink                        Param_LookAtOverride                                   (Parm, OutParm, NoDestructor)

void UABP_ElecPanda_Implementation_C::LookAtOverride(const struct FPoseLink& InPose, const struct FVector& Param_LookAtWorldLocation, struct FPoseLink* Param_LookAtOverride)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_ElecPanda_Implementation_C", "LookAtOverride");

	Params::ABP_ElecPanda_Implementation_C_LookAtOverride Parms{};

	Parms.InPose = std::move(InPose);
	Parms.Param_LookAtWorldLocation = std::move(Param_LookAtWorldLocation);

	UObject::ProcessEvent(Func, &Parms);

	if (Param_LookAtOverride != nullptr)
		*Param_LookAtOverride = std::move(Parms.Param_LookAtOverride);
}


// Function ABP_ElecPanda_Implementation.ABP_ElecPanda_Implementation_C.ExecuteUbergraph_ABP_ElecPanda_Implementation
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UABP_ElecPanda_Implementation_C::ExecuteUbergraph_ABP_ElecPanda_Implementation(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_ElecPanda_Implementation_C", "ExecuteUbergraph_ABP_ElecPanda_Implementation");

	Params::ABP_ElecPanda_Implementation_C_ExecuteUbergraph_ABP_ElecPanda_Implementation Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ABP_ElecPanda_Implementation.ABP_ElecPanda_Implementation_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_ElecPanda_Implementation_AnimGraphNode_ModifyBone_C60DFEC84E1EF8F9654E6791FEE2A4D1
// (BlueprintEvent)

void UABP_ElecPanda_Implementation_C::EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_ElecPanda_Implementation_AnimGraphNode_ModifyBone_C60DFEC84E1EF8F9654E6791FEE2A4D1()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_ElecPanda_Implementation_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_ElecPanda_Implementation_AnimGraphNode_ModifyBone_C60DFEC84E1EF8F9654E6791FEE2A4D1");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_ElecPanda_Implementation.ABP_ElecPanda_Implementation_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_ElecPanda_Implementation_AnimGraphNode_ModifyBone_B04BF725487338051D4BEA9094F52BDC
// (BlueprintEvent)

void UABP_ElecPanda_Implementation_C::EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_ElecPanda_Implementation_AnimGraphNode_ModifyBone_B04BF725487338051D4BEA9094F52BDC()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_ElecPanda_Implementation_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_ElecPanda_Implementation_AnimGraphNode_ModifyBone_B04BF725487338051D4BEA9094F52BDC");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_ElecPanda_Implementation.ABP_ElecPanda_Implementation_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_ElecPanda_Implementation_AnimGraphNode_ModifyBone_3273F77540B7195930F4D384AB9E4D03
// (BlueprintEvent)

void UABP_ElecPanda_Implementation_C::EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_ElecPanda_Implementation_AnimGraphNode_ModifyBone_3273F77540B7195930F4D384AB9E4D03()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_ElecPanda_Implementation_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_ElecPanda_Implementation_AnimGraphNode_ModifyBone_3273F77540B7195930F4D384AB9E4D03");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_ElecPanda_Implementation.ABP_ElecPanda_Implementation_C.AnimGraph
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FPoseLink                        Param_AnimGraph                                        (Parm, OutParm, NoDestructor)

void UABP_ElecPanda_Implementation_C::AnimGraph(struct FPoseLink* Param_AnimGraph)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_ElecPanda_Implementation_C", "AnimGraph");

	Params::ABP_ElecPanda_Implementation_C_AnimGraph Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Param_AnimGraph != nullptr)
		*Param_AnimGraph = std::move(Parms.Param_AnimGraph);
}


// Function ABP_ElecPanda_Implementation.ABP_ElecPanda_Implementation_C.AimingOverride
// (HasOutParams, BlueprintCallable)
// Parameters:
// struct FPoseLink                        DefaultPose                                            (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
// struct FRotator                         Param_AimRotator                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// struct FPoseLink                        Param_AimingOverride                                   (Parm, OutParm, NoDestructor)

void UABP_ElecPanda_Implementation_C::AimingOverride(const struct FPoseLink& DefaultPose, const struct FRotator& Param_AimRotator, struct FPoseLink* Param_AimingOverride)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_ElecPanda_Implementation_C", "AimingOverride");

	Params::ABP_ElecPanda_Implementation_C_AimingOverride Parms{};

	Parms.DefaultPose = std::move(DefaultPose);
	Parms.Param_AimRotator = std::move(Param_AimRotator);

	UObject::ProcessEvent(Func, &Parms);

	if (Param_AimingOverride != nullptr)
		*Param_AimingOverride = std::move(Parms.Param_AimingOverride);
}

}

