#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ALI_MonsterPhysics

#include "Basic.hpp"

#include "ALI_MonsterPhysics_classes.hpp"
#include "ALI_MonsterPhysics_parameters.hpp"


namespace SDK
{

// Function ALI_MonsterPhysics.ALI_MonsterPhysics_C.MonsterPhysics
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FPoseLink                        InPose                                                 (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
// struct FPoseLink                        Param_MonsterPhysics                                   (Parm, OutParm, NoDestructor)

void IALI_MonsterPhysics_C::MonsterPhysics(const struct FPoseLink& InPose, struct FPoseLink* Param_MonsterPhysics)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ALI_MonsterPhysics_C", "MonsterPhysics");

	Params::ALI_MonsterPhysics_C_MonsterPhysics Parms{};

	Parms.InPose = std::move(InPose);

	UObject::ProcessEvent(Func, &Parms);

	if (Param_MonsterPhysics != nullptr)
		*Param_MonsterPhysics = std::move(Parms.Param_MonsterPhysics);
}

}

