#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ActionUnique_ElecPanda_GatlingAttack

#include "Basic.hpp"

#include "BP_ActionUnique_ElecPanda_GatlingAttack_classes.hpp"
#include "BP_ActionUnique_ElecPanda_GatlingAttack_parameters.hpp"


namespace SDK
{

// Function BP_ActionUnique_ElecPanda_GatlingAttack.BP_ActionUnique_ElecPanda_GatlingAttack_C.CheckWeaponState
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    IsWeaponValid                                          (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_ActionUnique_ElecPanda_GatlingAttack_C::CheckWeaponState(bool* IsWeaponValid)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ActionUnique_ElecPanda_GatlingAttack_C", "CheckWeaponState");

	Params::BP_ActionUnique_ElecPanda_GatlingAttack_C_CheckWeaponState Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (IsWeaponValid != nullptr)
		*IsWeaponValid = Parms.IsWeaponValid;
}


// Function BP_ActionUnique_ElecPanda_GatlingAttack.BP_ActionUnique_ElecPanda_GatlingAttack_C.ElecShoot
// (BlueprintCallable, BlueprintEvent)

void UBP_ActionUnique_ElecPanda_GatlingAttack_C::ElecShoot()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ActionUnique_ElecPanda_GatlingAttack_C", "ElecShoot");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_ActionUnique_ElecPanda_GatlingAttack.BP_ActionUnique_ElecPanda_GatlingAttack_C.ExecuteUbergraph_BP_ActionUnique_ElecPanda_GatlingAttack
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_ActionUnique_ElecPanda_GatlingAttack_C::ExecuteUbergraph_BP_ActionUnique_ElecPanda_GatlingAttack(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ActionUnique_ElecPanda_GatlingAttack_C", "ExecuteUbergraph_BP_ActionUnique_ElecPanda_GatlingAttack");

	Params::BP_ActionUnique_ElecPanda_GatlingAttack_C_ExecuteUbergraph_BP_ActionUnique_ElecPanda_GatlingAttack Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_ActionUnique_ElecPanda_GatlingAttack.BP_ActionUnique_ElecPanda_GatlingAttack_C.OnBeginAction
// (Event, Public, BlueprintEvent)

void UBP_ActionUnique_ElecPanda_GatlingAttack_C::OnBeginAction()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ActionUnique_ElecPanda_GatlingAttack_C", "OnBeginAction");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_ActionUnique_ElecPanda_GatlingAttack.BP_ActionUnique_ElecPanda_GatlingAttack_C.OnBlendOut_1B1D39DF4F91178996FE139424596937
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_ActionUnique_ElecPanda_GatlingAttack_C::OnBlendOut_1B1D39DF4F91178996FE139424596937(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ActionUnique_ElecPanda_GatlingAttack_C", "OnBlendOut_1B1D39DF4F91178996FE139424596937");

	Params::BP_ActionUnique_ElecPanda_GatlingAttack_C_OnBlendOut_1B1D39DF4F91178996FE139424596937 Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_ActionUnique_ElecPanda_GatlingAttack.BP_ActionUnique_ElecPanda_GatlingAttack_C.OnCompleted_1B1D39DF4F91178996FE139424596937
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_ActionUnique_ElecPanda_GatlingAttack_C::OnCompleted_1B1D39DF4F91178996FE139424596937(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ActionUnique_ElecPanda_GatlingAttack_C", "OnCompleted_1B1D39DF4F91178996FE139424596937");

	Params::BP_ActionUnique_ElecPanda_GatlingAttack_C_OnCompleted_1B1D39DF4F91178996FE139424596937 Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_ActionUnique_ElecPanda_GatlingAttack.BP_ActionUnique_ElecPanda_GatlingAttack_C.OnEndAction
// (Event, Public, BlueprintEvent)

void UBP_ActionUnique_ElecPanda_GatlingAttack_C::OnEndAction()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ActionUnique_ElecPanda_GatlingAttack_C", "OnEndAction");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_ActionUnique_ElecPanda_GatlingAttack.BP_ActionUnique_ElecPanda_GatlingAttack_C.OnInterrupted_1B1D39DF4F91178996FE139424596937
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_ActionUnique_ElecPanda_GatlingAttack_C::OnInterrupted_1B1D39DF4F91178996FE139424596937(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ActionUnique_ElecPanda_GatlingAttack_C", "OnInterrupted_1B1D39DF4F91178996FE139424596937");

	Params::BP_ActionUnique_ElecPanda_GatlingAttack_C_OnInterrupted_1B1D39DF4F91178996FE139424596937 Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_ActionUnique_ElecPanda_GatlingAttack.BP_ActionUnique_ElecPanda_GatlingAttack_C.OnNotifyBegin_1B1D39DF4F91178996FE139424596937
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_ActionUnique_ElecPanda_GatlingAttack_C::OnNotifyBegin_1B1D39DF4F91178996FE139424596937(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ActionUnique_ElecPanda_GatlingAttack_C", "OnNotifyBegin_1B1D39DF4F91178996FE139424596937");

	Params::BP_ActionUnique_ElecPanda_GatlingAttack_C_OnNotifyBegin_1B1D39DF4F91178996FE139424596937 Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_ActionUnique_ElecPanda_GatlingAttack.BP_ActionUnique_ElecPanda_GatlingAttack_C.OnNotifyEnd_1B1D39DF4F91178996FE139424596937
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_ActionUnique_ElecPanda_GatlingAttack_C::OnNotifyEnd_1B1D39DF4F91178996FE139424596937(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ActionUnique_ElecPanda_GatlingAttack_C", "OnNotifyEnd_1B1D39DF4F91178996FE139424596937");

	Params::BP_ActionUnique_ElecPanda_GatlingAttack_C_OnNotifyEnd_1B1D39DF4F91178996FE139424596937 Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_ActionUnique_ElecPanda_GatlingAttack.BP_ActionUnique_ElecPanda_GatlingAttack_C.Shooting
// (BlueprintCallable, BlueprintEvent)

void UBP_ActionUnique_ElecPanda_GatlingAttack_C::Shooting()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ActionUnique_ElecPanda_GatlingAttack_C", "Shooting");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_ActionUnique_ElecPanda_GatlingAttack.BP_ActionUnique_ElecPanda_GatlingAttack_C.ShootSkill Bullet
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FPalWeaponBulletHijackInfo       HijackBulletInfo                                       (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)

void UBP_ActionUnique_ElecPanda_GatlingAttack_C::ShootSkill_Bullet(const struct FPalWeaponBulletHijackInfo& HijackBulletInfo)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ActionUnique_ElecPanda_GatlingAttack_C", "ShootSkill Bullet");

	Params::BP_ActionUnique_ElecPanda_GatlingAttack_C_ShootSkill_Bullet Parms{};

	Parms.HijackBulletInfo = std::move(HijackBulletInfo);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_ActionUnique_ElecPanda_GatlingAttack.BP_ActionUnique_ElecPanda_GatlingAttack_C.StartShort
// (BlueprintCallable, BlueprintEvent)

void UBP_ActionUnique_ElecPanda_GatlingAttack_C::StartShort()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ActionUnique_ElecPanda_GatlingAttack_C", "StartShort");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_ActionUnique_ElecPanda_GatlingAttack.BP_ActionUnique_ElecPanda_GatlingAttack_C.TickAction
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaTime                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_ActionUnique_ElecPanda_GatlingAttack_C::TickAction(float DeltaTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ActionUnique_ElecPanda_GatlingAttack_C", "TickAction");

	Params::BP_ActionUnique_ElecPanda_GatlingAttack_C_TickAction Parms{};

	Parms.DeltaTime = DeltaTime;

	UObject::ProcessEvent(Func, &Parms);
}

}

