#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_BackWeapon_GuidedMissileLauncher

#include "Basic.hpp"

#include "BP_BackWeapon_RocketLauncher_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_BackWeapon_GuidedMissileLauncher.BP_BackWeapon_GuidedMissileLauncher_C
// 0x0000 (0x0318 - 0x0318)
class ABP_BackWeapon_GuidedMissileLauncher_C final : public ABP_BackWeapon_RocketLauncher_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_BackWeapon_GuidedMissileLauncher_C">();
	}
	static class ABP_BackWeapon_GuidedMissileLauncher_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_BackWeapon_GuidedMissileLauncher_C>();
	}
};
static_assert(alignof(ABP_BackWeapon_GuidedMissileLauncher_C) == 0x000008, "Wrong alignment on ABP_BackWeapon_GuidedMissileLauncher_C");
static_assert(sizeof(ABP_BackWeapon_GuidedMissileLauncher_C) == 0x000318, "Wrong size on ABP_BackWeapon_GuidedMissileLauncher_C");

}

