#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_DropWeaponPart

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"


namespace SDK::Params
{

// Function BP_DropWeaponPart.BP_DropWeaponPart_C.ExecuteUbergraph_BP_DropWeaponPart
// 0x0030 (0x0030 - 0x0000)
struct BP_DropWeaponPart_C_ExecuteUbergraph_BP_DropWeaponPart final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_536B[0x4];                                     // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UStaticMesh*                            K2Node_CustomEvent_Mesh;                           // 0x0008(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FVector                                K2Node_CustomEvent_Velocity;                       // 0x0010(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_SetStaticMesh_ReturnValue;                // 0x0028(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_DropWeaponPart_C_ExecuteUbergraph_BP_DropWeaponPart) == 0x000008, "Wrong alignment on BP_DropWeaponPart_C_ExecuteUbergraph_BP_DropWeaponPart");
static_assert(sizeof(BP_DropWeaponPart_C_ExecuteUbergraph_BP_DropWeaponPart) == 0x000030, "Wrong size on BP_DropWeaponPart_C_ExecuteUbergraph_BP_DropWeaponPart");
static_assert(offsetof(BP_DropWeaponPart_C_ExecuteUbergraph_BP_DropWeaponPart, EntryPoint) == 0x000000, "Member 'BP_DropWeaponPart_C_ExecuteUbergraph_BP_DropWeaponPart::EntryPoint' has a wrong offset!");
static_assert(offsetof(BP_DropWeaponPart_C_ExecuteUbergraph_BP_DropWeaponPart, K2Node_CustomEvent_Mesh) == 0x000008, "Member 'BP_DropWeaponPart_C_ExecuteUbergraph_BP_DropWeaponPart::K2Node_CustomEvent_Mesh' has a wrong offset!");
static_assert(offsetof(BP_DropWeaponPart_C_ExecuteUbergraph_BP_DropWeaponPart, K2Node_CustomEvent_Velocity) == 0x000010, "Member 'BP_DropWeaponPart_C_ExecuteUbergraph_BP_DropWeaponPart::K2Node_CustomEvent_Velocity' has a wrong offset!");
static_assert(offsetof(BP_DropWeaponPart_C_ExecuteUbergraph_BP_DropWeaponPart, CallFunc_SetStaticMesh_ReturnValue) == 0x000028, "Member 'BP_DropWeaponPart_C_ExecuteUbergraph_BP_DropWeaponPart::CallFunc_SetStaticMesh_ReturnValue' has a wrong offset!");

// Function BP_DropWeaponPart.BP_DropWeaponPart_C.CustomBegin
// 0x0020 (0x0020 - 0x0000)
struct BP_DropWeaponPart_C_CustomBegin final
{
public:
	class UStaticMesh*                            Mesh;                                              // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FVector                                Velocity;                                          // 0x0008(0x0018)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_DropWeaponPart_C_CustomBegin) == 0x000008, "Wrong alignment on BP_DropWeaponPart_C_CustomBegin");
static_assert(sizeof(BP_DropWeaponPart_C_CustomBegin) == 0x000020, "Wrong size on BP_DropWeaponPart_C_CustomBegin");
static_assert(offsetof(BP_DropWeaponPart_C_CustomBegin, Mesh) == 0x000000, "Member 'BP_DropWeaponPart_C_CustomBegin::Mesh' has a wrong offset!");
static_assert(offsetof(BP_DropWeaponPart_C_CustomBegin, Velocity) == 0x000008, "Member 'BP_DropWeaponPart_C_CustomBegin::Velocity' has a wrong offset!");

}

