#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_FireKirin_Normal

#include "Basic.hpp"

#include "BP_FireKirin_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_FireKirin_Normal.BP_FireKirin_Normal_C
// 0x0000 (0x0A90 - 0x0A90)
class ABP_FireKirin_Normal_C final : public ABP_FireKirin_C
{
public:
	class UBP_PalRideMarkerSaddle_C*              BP_PalRideMarkerSaddle;                            // 0x0A88(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_FireKirin_Normal_C">();
	}
	static class ABP_FireKirin_Normal_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_FireKirin_Normal_C>();
	}
};
static_assert(alignof(ABP_FireKirin_Normal_C) == 0x000010, "Wrong alignment on ABP_FireKirin_Normal_C");
static_assert(sizeof(ABP_FireKirin_Normal_C) == 0x000A90, "Wrong size on ABP_FireKirin_Normal_C");
static_assert(offsetof(ABP_FireKirin_Normal_C, BP_PalRideMarkerSaddle) == 0x000A88, "Member 'ABP_FireKirin_Normal_C::BP_PalRideMarkerSaddle' has a wrong offset!");

}

