#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_FlamethrowBackTank

#include "Basic.hpp"

#include "Pal_structs.hpp"
#include "Engine_structs.hpp"
#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_FlamethrowBackTank.BP_FlamethrowBackTank_C
// 0x0038 (0x02C8 - 0x0290)
class ABP_FlamethrowBackTank_C final : public AActor
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0290(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UNiagaraComponent*                      NS_UniqueSkill_FlameBuffalo_FlameHorn_End;         // 0x0298(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UBP_PalDamageExplodeComponent_C*        BP_PalDamageExplodeComponent;                      // 0x02A0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   StaticMesh;                                        // 0x02A8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UCapsuleComponent*                      CapsuleCollision;                                  // 0x02B0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 HitBulletAttacker;                                 // 0x02B8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	bool                                          IsBurn;                                            // 0x02C0(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void SelfDelete(const struct FPalDeadInfo& DeadInfo);
	void RemoveStatus(const class UPalStatusComponent* StatusComponent, EPalStatusID StatusId);
	void ReceiveTick(float DeltaSeconds);
	void OnOwnerDelete(class AActor* DestroyedActor);
	void OnEx();
	void OnDamage(const struct FPalDamageInfo& DamageInfo);
	void ExecuteUbergraph_BP_FlamethrowBackTank(int32 EntryPoint);
	void AddStatus(const class UPalStatusComponent* StatusComponent, EPalStatusID StatusId, class UPalStatusBase* Status);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_FlamethrowBackTank_C">();
	}
	static class ABP_FlamethrowBackTank_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_FlamethrowBackTank_C>();
	}
};
static_assert(alignof(ABP_FlamethrowBackTank_C) == 0x000008, "Wrong alignment on ABP_FlamethrowBackTank_C");
static_assert(sizeof(ABP_FlamethrowBackTank_C) == 0x0002C8, "Wrong size on ABP_FlamethrowBackTank_C");
static_assert(offsetof(ABP_FlamethrowBackTank_C, UberGraphFrame) == 0x000290, "Member 'ABP_FlamethrowBackTank_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(ABP_FlamethrowBackTank_C, NS_UniqueSkill_FlameBuffalo_FlameHorn_End) == 0x000298, "Member 'ABP_FlamethrowBackTank_C::NS_UniqueSkill_FlameBuffalo_FlameHorn_End' has a wrong offset!");
static_assert(offsetof(ABP_FlamethrowBackTank_C, BP_PalDamageExplodeComponent) == 0x0002A0, "Member 'ABP_FlamethrowBackTank_C::BP_PalDamageExplodeComponent' has a wrong offset!");
static_assert(offsetof(ABP_FlamethrowBackTank_C, StaticMesh) == 0x0002A8, "Member 'ABP_FlamethrowBackTank_C::StaticMesh' has a wrong offset!");
static_assert(offsetof(ABP_FlamethrowBackTank_C, CapsuleCollision) == 0x0002B0, "Member 'ABP_FlamethrowBackTank_C::CapsuleCollision' has a wrong offset!");
static_assert(offsetof(ABP_FlamethrowBackTank_C, HitBulletAttacker) == 0x0002B8, "Member 'ABP_FlamethrowBackTank_C::HitBulletAttacker' has a wrong offset!");
static_assert(offsetof(ABP_FlamethrowBackTank_C, IsBurn) == 0x0002C0, "Member 'ABP_FlamethrowBackTank_C::IsBurn' has a wrong offset!");

}

