#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Flamethrower_NPC

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"


namespace SDK::Params
{

// Function BP_Flamethrower_NPC.BP_Flamethrower_NPC_C.TickShootingFire
// 0x0008 (0x0008 - 0x0000)
struct BP_Flamethrower_NPC_C_TickShootingFire final
{
public:
	double                                        DeltaTime;                                         // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_Flamethrower_NPC_C_TickShootingFire) == 0x000008, "Wrong alignment on BP_Flamethrower_NPC_C_TickShootingFire");
static_assert(sizeof(BP_Flamethrower_NPC_C_TickShootingFire) == 0x000008, "Wrong size on BP_Flamethrower_NPC_C_TickShootingFire");
static_assert(offsetof(BP_Flamethrower_NPC_C_TickShootingFire, DeltaTime) == 0x000000, "Member 'BP_Flamethrower_NPC_C_TickShootingFire::DeltaTime' has a wrong offset!");

// Function BP_Flamethrower_NPC.BP_Flamethrower_NPC_C.ExecuteUbergraph_BP_Flamethrower_NPC
// 0x0090 (0x0090 - 0x0000)
struct BP_Flamethrower_NPC_C_ExecuteUbergraph_BP_Flamethrower_NPC final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_35AE[0xC];                                     // 0x0004(0x000C)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTransform                             CallFunc_MakeTransform_ReturnValue;                // 0x0010(0x0060)(IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsServer_ReturnValue;                     // 0x0070(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_35AF[0x7];                                     // 0x0071(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class AActor*                                 CallFunc_GetOwner_ReturnValue;                     // 0x0078(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue; // 0x0080(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class ABP_FlamethrowBackTank_C*               CallFunc_FinishSpawningActor_ReturnValue;          // 0x0088(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_Flamethrower_NPC_C_ExecuteUbergraph_BP_Flamethrower_NPC) == 0x000010, "Wrong alignment on BP_Flamethrower_NPC_C_ExecuteUbergraph_BP_Flamethrower_NPC");
static_assert(sizeof(BP_Flamethrower_NPC_C_ExecuteUbergraph_BP_Flamethrower_NPC) == 0x000090, "Wrong size on BP_Flamethrower_NPC_C_ExecuteUbergraph_BP_Flamethrower_NPC");
static_assert(offsetof(BP_Flamethrower_NPC_C_ExecuteUbergraph_BP_Flamethrower_NPC, EntryPoint) == 0x000000, "Member 'BP_Flamethrower_NPC_C_ExecuteUbergraph_BP_Flamethrower_NPC::EntryPoint' has a wrong offset!");
static_assert(offsetof(BP_Flamethrower_NPC_C_ExecuteUbergraph_BP_Flamethrower_NPC, CallFunc_MakeTransform_ReturnValue) == 0x000010, "Member 'BP_Flamethrower_NPC_C_ExecuteUbergraph_BP_Flamethrower_NPC::CallFunc_MakeTransform_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Flamethrower_NPC_C_ExecuteUbergraph_BP_Flamethrower_NPC, CallFunc_IsServer_ReturnValue) == 0x000070, "Member 'BP_Flamethrower_NPC_C_ExecuteUbergraph_BP_Flamethrower_NPC::CallFunc_IsServer_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Flamethrower_NPC_C_ExecuteUbergraph_BP_Flamethrower_NPC, CallFunc_GetOwner_ReturnValue) == 0x000078, "Member 'BP_Flamethrower_NPC_C_ExecuteUbergraph_BP_Flamethrower_NPC::CallFunc_GetOwner_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Flamethrower_NPC_C_ExecuteUbergraph_BP_Flamethrower_NPC, CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue) == 0x000080, "Member 'BP_Flamethrower_NPC_C_ExecuteUbergraph_BP_Flamethrower_NPC::CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Flamethrower_NPC_C_ExecuteUbergraph_BP_Flamethrower_NPC, CallFunc_FinishSpawningActor_ReturnValue) == 0x000088, "Member 'BP_Flamethrower_NPC_C_ExecuteUbergraph_BP_Flamethrower_NPC::CallFunc_FinishSpawningActor_ReturnValue' has a wrong offset!");

// Function BP_Flamethrower_NPC.BP_Flamethrower_NPC_C.GetWeaponDamage
// 0x0008 (0x0008 - 0x0000)
struct BP_Flamethrower_NPC_C_GetWeaponDamage final
{
public:
	int32                                         ReturnValue;                                       // 0x0000(0x0004)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_CalcNPCWeaponDamage_ReturnValue;          // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_Flamethrower_NPC_C_GetWeaponDamage) == 0x000004, "Wrong alignment on BP_Flamethrower_NPC_C_GetWeaponDamage");
static_assert(sizeof(BP_Flamethrower_NPC_C_GetWeaponDamage) == 0x000008, "Wrong size on BP_Flamethrower_NPC_C_GetWeaponDamage");
static_assert(offsetof(BP_Flamethrower_NPC_C_GetWeaponDamage, ReturnValue) == 0x000000, "Member 'BP_Flamethrower_NPC_C_GetWeaponDamage::ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Flamethrower_NPC_C_GetWeaponDamage, CallFunc_CalcNPCWeaponDamage_ReturnValue) == 0x000004, "Member 'BP_Flamethrower_NPC_C_GetWeaponDamage::CallFunc_CalcNPCWeaponDamage_ReturnValue' has a wrong offset!");

// Function BP_Flamethrower_NPC.BP_Flamethrower_NPC_C.GetNPCWeaponDamage
// 0x0004 (0x0004 - 0x0000)
struct BP_Flamethrower_NPC_C_GetNPCWeaponDamage final
{
public:
	int32                                         ReturnValue;                                       // 0x0000(0x0004)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_Flamethrower_NPC_C_GetNPCWeaponDamage) == 0x000004, "Wrong alignment on BP_Flamethrower_NPC_C_GetNPCWeaponDamage");
static_assert(sizeof(BP_Flamethrower_NPC_C_GetNPCWeaponDamage) == 0x000004, "Wrong size on BP_Flamethrower_NPC_C_GetNPCWeaponDamage");
static_assert(offsetof(BP_Flamethrower_NPC_C_GetNPCWeaponDamage, ReturnValue) == 0x000000, "Member 'BP_Flamethrower_NPC_C_GetNPCWeaponDamage::ReturnValue' has a wrong offset!");

}

