#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_GrenadeLauncher

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "BP_AssaultRifleBase_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_GrenadeLauncher.BP_GrenadeLauncher_C
// 0x0020 (0x05D0 - 0x05B0)
class ABP_GrenadeLauncher_C : public ABP_AssaultRifleBase_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_BP_GrenadeLauncher_C;               // 0x05B0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class USkeletalMeshComponent*                 SkeletalMesh;                                      // 0x05B8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UMaterialInstanceDynamic*               RocketMask;                                        // 0x05C0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	bool                                          IsCoolTime;                                        // 0x05C8(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ShootBullet();
	void ResetCoolTime();
	void ReceiveTick(float DeltaSeconds);
	void ReceiveBeginPlay();
	void PlayFireSound();
	void OnShoot();
	void OnReloadStart();
	void OnReload(int32 bulletsNum);
	void OnPullTrigger();
	void OnEndShootAnimation(class UAnimMontage* Montage);
	void OnDetachWeapon(class AActor* DetachActor);
	void OnAttachWeapon(class AActor* AttachActor);
	void IsUseRightHandAttach(bool* IsUse);
	void GetShootInterval(double* Time);
	void GetMuzzleRotator(struct FRotator* Rotator);
	void GetMuzzleLocation(struct FVector* MuzzleLocation);
	void GetMuzzleEffect(class UNiagaraSystem** NewParam);
	void GetInitializeInterval(double* Time);
	void GetBulletClass(class UClass** NewParam);
	void GetBlurAngle(double* Angle);
	void GetAimingBlurAngle(double* Angle);
	void Get_Right_Hand_Location(struct FVector* RightHandLocation);
	void ExecuteUbergraph_BP_GrenadeLauncher(int32 EntryPoint);

	bool IsUseLeftHandAttach() const;
	struct FTransform GetLeftHandTransform() const;

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_GrenadeLauncher_C">();
	}
	static class ABP_GrenadeLauncher_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_GrenadeLauncher_C>();
	}
};
static_assert(alignof(ABP_GrenadeLauncher_C) == 0x000008, "Wrong alignment on ABP_GrenadeLauncher_C");
static_assert(sizeof(ABP_GrenadeLauncher_C) == 0x0005D0, "Wrong size on ABP_GrenadeLauncher_C");
static_assert(offsetof(ABP_GrenadeLauncher_C, UberGraphFrame_BP_GrenadeLauncher_C) == 0x0005B0, "Member 'ABP_GrenadeLauncher_C::UberGraphFrame_BP_GrenadeLauncher_C' has a wrong offset!");
static_assert(offsetof(ABP_GrenadeLauncher_C, SkeletalMesh) == 0x0005B8, "Member 'ABP_GrenadeLauncher_C::SkeletalMesh' has a wrong offset!");
static_assert(offsetof(ABP_GrenadeLauncher_C, RocketMask) == 0x0005C0, "Member 'ABP_GrenadeLauncher_C::RocketMask' has a wrong offset!");
static_assert(offsetof(ABP_GrenadeLauncher_C, IsCoolTime) == 0x0005C8, "Member 'ABP_GrenadeLauncher_C::IsCoolTime' has a wrong offset!");

}

