#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_GrenadeLauncher_NPC

#include "Basic.hpp"

#include "BP_GrenadeLauncher_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_GrenadeLauncher_NPC.BP_GrenadeLauncher_NPC_C
// 0x0000 (0x05D0 - 0x05D0)
class ABP_GrenadeLauncher_NPC_C final : public ABP_GrenadeLauncher_C
{
public:
	int32 GetWeaponDamage() const;
	int32 GetNPCWeaponDamage() const;

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_GrenadeLauncher_NPC_C">();
	}
	static class ABP_GrenadeLauncher_NPC_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_GrenadeLauncher_NPC_C>();
	}
};
static_assert(alignof(ABP_GrenadeLauncher_NPC_C) == 0x000008, "Wrong alignment on ABP_GrenadeLauncher_NPC_C");
static_assert(sizeof(ABP_GrenadeLauncher_NPC_C) == 0x0005D0, "Wrong size on ABP_GrenadeLauncher_NPC_C");

}

