#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_HomingMissile_MissileLauncher_Big

#include "Basic.hpp"

#include "BP_HomingMissile_MissileLauncher_Big_classes.hpp"
#include "BP_HomingMissile_MissileLauncher_Big_parameters.hpp"


namespace SDK
{

// Function BP_HomingMissile_MissileLauncher_Big.BP_HomingMissile_MissileLauncher_Big_C.GetExplosionClass
// (Protected, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class UClass*                           ExplosionClass                                         (Parm, OutParm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void ABP_HomingMissile_MissileLauncher_Big_C::GetExplosionClass(class UClass** ExplosionClass)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_HomingMissile_MissileLauncher_Big_C", "GetExplosionClass");

	Params::BP_HomingMissile_MissileLauncher_Big_C_GetExplosionClass Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (ExplosionClass != nullptr)
		*ExplosionClass = Parms.ExplosionClass;
}

}

