#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_HomingMissile_MissileLauncher_Big

#include "Basic.hpp"


namespace SDK::Params
{

// Function BP_HomingMissile_MissileLauncher_Big.BP_HomingMissile_MissileLauncher_Big_C.GetExplosionClass
// 0x0008 (0x0008 - 0x0000)
struct BP_HomingMissile_MissileLauncher_Big_C_GetExplosionClass final
{
public:
	class UClass*                                 ExplosionClass;                                    // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_HomingMissile_MissileLauncher_Big_C_GetExplosionClass) == 0x000008, "Wrong alignment on BP_HomingMissile_MissileLauncher_Big_C_GetExplosionClass");
static_assert(sizeof(BP_HomingMissile_MissileLauncher_Big_C_GetExplosionClass) == 0x000008, "Wrong size on BP_HomingMissile_MissileLauncher_Big_C_GetExplosionClass");
static_assert(offsetof(BP_HomingMissile_MissileLauncher_Big_C_GetExplosionClass, ExplosionClass) == 0x000000, "Member 'BP_HomingMissile_MissileLauncher_Big_C_GetExplosionClass::ExplosionClass' has a wrong offset!");

}

