#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_MultiGuidedMissileLauncher

#include "Basic.hpp"

#include "BP_GuidedMissileLauncher_classes.hpp"
#include "Engine_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_MultiGuidedMissileLauncher.BP_MultiGuidedMissileLauncher_C
// 0x0030 (0x0618 - 0x05E8)
class ABP_MultiGuidedMissileLauncher_C : public ABP_GuidedMissileLauncher_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_BP_MultiGuidedMissileLauncher_C;    // 0x05E8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UBP_MultiMissileAmmo_C*                 BP_MultiMissileAmmo3;                              // 0x05F0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UBP_MultiMissileAmmo_C*                 BP_MultiMissileAmmo2;                              // 0x05F8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UBP_MultiMissileAmmo_C*                 BP_MultiMissileAmmo1;                              // 0x0600(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UBP_MultiMissileAmmo_C*                 BP_MultiMissileAmmo;                               // 0x0608(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	bool                                          IsCoolTime;                                        // 0x0610(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void OnShoot();
	void OnReloadStart();
	void GetMuzzleEffect(class UNiagaraSystem** NewParam);
	void GetBulletClass(class UClass** NewParam);
	void ResetCoolTime();
	void OnPullTrigger();
	void GetMuzzleLocation(struct FVector* MuzzleLocation);
	void GetBackFireLocation(struct FVector* Location, struct FRotator* Rotation);
	void ExecuteUbergraph_BP_MultiGuidedMissileLauncher(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_MultiGuidedMissileLauncher_C">();
	}
	static class ABP_MultiGuidedMissileLauncher_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_MultiGuidedMissileLauncher_C>();
	}
};
static_assert(alignof(ABP_MultiGuidedMissileLauncher_C) == 0x000008, "Wrong alignment on ABP_MultiGuidedMissileLauncher_C");
static_assert(sizeof(ABP_MultiGuidedMissileLauncher_C) == 0x000618, "Wrong size on ABP_MultiGuidedMissileLauncher_C");
static_assert(offsetof(ABP_MultiGuidedMissileLauncher_C, UberGraphFrame_BP_MultiGuidedMissileLauncher_C) == 0x0005E8, "Member 'ABP_MultiGuidedMissileLauncher_C::UberGraphFrame_BP_MultiGuidedMissileLauncher_C' has a wrong offset!");
static_assert(offsetof(ABP_MultiGuidedMissileLauncher_C, BP_MultiMissileAmmo3) == 0x0005F0, "Member 'ABP_MultiGuidedMissileLauncher_C::BP_MultiMissileAmmo3' has a wrong offset!");
static_assert(offsetof(ABP_MultiGuidedMissileLauncher_C, BP_MultiMissileAmmo2) == 0x0005F8, "Member 'ABP_MultiGuidedMissileLauncher_C::BP_MultiMissileAmmo2' has a wrong offset!");
static_assert(offsetof(ABP_MultiGuidedMissileLauncher_C, BP_MultiMissileAmmo1) == 0x000600, "Member 'ABP_MultiGuidedMissileLauncher_C::BP_MultiMissileAmmo1' has a wrong offset!");
static_assert(offsetof(ABP_MultiGuidedMissileLauncher_C, BP_MultiMissileAmmo) == 0x000608, "Member 'ABP_MultiGuidedMissileLauncher_C::BP_MultiMissileAmmo' has a wrong offset!");
static_assert(offsetof(ABP_MultiGuidedMissileLauncher_C, IsCoolTime) == 0x000610, "Member 'ABP_MultiGuidedMissileLauncher_C::IsCoolTime' has a wrong offset!");

}

