#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_MultiMissileAmmo

#include "Basic.hpp"

#include "BP_MultiMissileAmmo_classes.hpp"
#include "BP_MultiMissileAmmo_parameters.hpp"


namespace SDK
{

// Function BP_MultiMissileAmmo.BP_MultiMissileAmmo_C.SetAmmoHidden
// (Public, BlueprintCallable, BlueprintEvent)

void UBP_MultiMissileAmmo_C::SetAmmoHidden()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_MultiMissileAmmo_C", "SetAmmoHidden");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_MultiMissileAmmo.BP_MultiMissileAmmo_C.ReceiveBeginPlay
// (Event, Public, BlueprintEvent)

void UBP_MultiMissileAmmo_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_MultiMissileAmmo_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_MultiMissileAmmo.BP_MultiMissileAmmo_C.ExecuteUbergraph_BP_MultiMissileAmmo
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_MultiMissileAmmo_C::ExecuteUbergraph_BP_MultiMissileAmmo(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_MultiMissileAmmo_C", "ExecuteUbergraph_BP_MultiMissileAmmo");

	Params::BP_MultiMissileAmmo_C_ExecuteUbergraph_BP_MultiMissileAmmo Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_MultiMissileAmmo.BP_MultiMissileAmmo_C.Delegate_Reload
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   bulletsNum                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_MultiMissileAmmo_C::Delegate_Reload(int32 bulletsNum)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_MultiMissileAmmo_C", "Delegate_Reload");

	Params::BP_MultiMissileAmmo_C_Delegate_Reload Parms{};

	Parms.bulletsNum = bulletsNum;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_MultiMissileAmmo.BP_MultiMissileAmmo_C.Delegate_OnShoot
// (BlueprintCallable, BlueprintEvent)

void UBP_MultiMissileAmmo_C::Delegate_OnShoot()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_MultiMissileAmmo_C", "Delegate_OnShoot");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_MultiMissileAmmo.BP_MultiMissileAmmo_C.Delegate_OnAttach
// (BlueprintCallable, BlueprintEvent)

void UBP_MultiMissileAmmo_C::Delegate_OnAttach()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_MultiMissileAmmo_C", "Delegate_OnAttach");

	UObject::ProcessEvent(Func, nullptr);
}

}

