#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_MultiGuidedMissileLauncher

#include "Basic.hpp"

#include "BP_MultiGuidedMissileLauncher_classes.hpp"
#include "BP_MultiGuidedMissileLauncher_parameters.hpp"


namespace SDK
{

// Function BP_MultiGuidedMissileLauncher.BP_MultiGuidedMissileLauncher_C.OnShoot
// (Public, BlueprintCallable, BlueprintEvent)

void ABP_MultiGuidedMissileLauncher_C::OnShoot()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_MultiGuidedMissileLauncher_C", "OnShoot");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_MultiGuidedMissileLauncher.BP_MultiGuidedMissileLauncher_C.OnReloadStart
// (Event, Public, BlueprintEvent)

void ABP_MultiGuidedMissileLauncher_C::OnReloadStart()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_MultiGuidedMissileLauncher_C", "OnReloadStart");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_MultiGuidedMissileLauncher.BP_MultiGuidedMissileLauncher_C.GetMuzzleEffect
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class UNiagaraSystem*                   NewParam                                               (Parm, OutParm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void ABP_MultiGuidedMissileLauncher_C::GetMuzzleEffect(class UNiagaraSystem** NewParam)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_MultiGuidedMissileLauncher_C", "GetMuzzleEffect");

	Params::BP_MultiGuidedMissileLauncher_C_GetMuzzleEffect Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (NewParam != nullptr)
		*NewParam = Parms.NewParam;
}


// Function BP_MultiGuidedMissileLauncher.BP_MultiGuidedMissileLauncher_C.GetBulletClass
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class UClass*                           NewParam                                               (Parm, OutParm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void ABP_MultiGuidedMissileLauncher_C::GetBulletClass(class UClass** NewParam)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_MultiGuidedMissileLauncher_C", "GetBulletClass");

	Params::BP_MultiGuidedMissileLauncher_C_GetBulletClass Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (NewParam != nullptr)
		*NewParam = Parms.NewParam;
}


// Function BP_MultiGuidedMissileLauncher.BP_MultiGuidedMissileLauncher_C.ResetCoolTime
// (BlueprintCallable, BlueprintEvent)

void ABP_MultiGuidedMissileLauncher_C::ResetCoolTime()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_MultiGuidedMissileLauncher_C", "ResetCoolTime");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_MultiGuidedMissileLauncher.BP_MultiGuidedMissileLauncher_C.OnPullTrigger
// (Event, Public, BlueprintCallable, BlueprintEvent)

void ABP_MultiGuidedMissileLauncher_C::OnPullTrigger()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_MultiGuidedMissileLauncher_C", "OnPullTrigger");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_MultiGuidedMissileLauncher.BP_MultiGuidedMissileLauncher_C.GetMuzzleLocation
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// struct FVector                          MuzzleLocation                                         (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_MultiGuidedMissileLauncher_C::GetMuzzleLocation(struct FVector* MuzzleLocation)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_MultiGuidedMissileLauncher_C", "GetMuzzleLocation");

	Params::BP_MultiGuidedMissileLauncher_C_GetMuzzleLocation Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (MuzzleLocation != nullptr)
		*MuzzleLocation = std::move(Parms.MuzzleLocation);
}


// Function BP_MultiGuidedMissileLauncher.BP_MultiGuidedMissileLauncher_C.GetBackFireLocation
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// struct FVector                          Location                                               (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FRotator                         Rotation                                               (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ABP_MultiGuidedMissileLauncher_C::GetBackFireLocation(struct FVector* Location, struct FRotator* Rotation)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_MultiGuidedMissileLauncher_C", "GetBackFireLocation");

	Params::BP_MultiGuidedMissileLauncher_C_GetBackFireLocation Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Location != nullptr)
		*Location = std::move(Parms.Location);

	if (Rotation != nullptr)
		*Rotation = std::move(Parms.Rotation);
}


// Function BP_MultiGuidedMissileLauncher.BP_MultiGuidedMissileLauncher_C.ExecuteUbergraph_BP_MultiGuidedMissileLauncher
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_MultiGuidedMissileLauncher_C::ExecuteUbergraph_BP_MultiGuidedMissileLauncher(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_MultiGuidedMissileLauncher_C", "ExecuteUbergraph_BP_MultiGuidedMissileLauncher");

	Params::BP_MultiGuidedMissileLauncher_C_ExecuteUbergraph_BP_MultiGuidedMissileLauncher Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

