#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_MapObject_SupplyDrop

#include "Basic.hpp"


namespace SDK::Params
{

// Function BP_MapObject_SupplyDrop.BP_MapObject_SupplyDrop_C.BP_OnSetConcreteModel
// 0x0008 (0x0008 - 0x0000)
struct BP_MapObject_SupplyDrop_C_BP_OnSetConcreteModel final
{
public:
	class UPalMapObjectConcreteModelBase*         ConcreteModel;                                     // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_MapObject_SupplyDrop_C_BP_OnSetConcreteModel) == 0x000008, "Wrong alignment on BP_MapObject_SupplyDrop_C_BP_OnSetConcreteModel");
static_assert(sizeof(BP_MapObject_SupplyDrop_C_BP_OnSetConcreteModel) == 0x000008, "Wrong size on BP_MapObject_SupplyDrop_C_BP_OnSetConcreteModel");
static_assert(offsetof(BP_MapObject_SupplyDrop_C_BP_OnSetConcreteModel, ConcreteModel) == 0x000000, "Member 'BP_MapObject_SupplyDrop_C_BP_OnSetConcreteModel::ConcreteModel' has a wrong offset!");

// Function BP_MapObject_SupplyDrop.BP_MapObject_SupplyDrop_C.ExecuteUbergraph_BP_MapObject_SupplyDrop
// 0x0010 (0x0010 - 0x0000)
struct BP_MapObject_SupplyDrop_C_ExecuteUbergraph_BP_MapObject_SupplyDrop final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3B3B[0x4];                                     // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UPalMapObjectConcreteModelBase*         K2Node_Event_ConcreteModel;                        // 0x0008(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_MapObject_SupplyDrop_C_ExecuteUbergraph_BP_MapObject_SupplyDrop) == 0x000008, "Wrong alignment on BP_MapObject_SupplyDrop_C_ExecuteUbergraph_BP_MapObject_SupplyDrop");
static_assert(sizeof(BP_MapObject_SupplyDrop_C_ExecuteUbergraph_BP_MapObject_SupplyDrop) == 0x000010, "Wrong size on BP_MapObject_SupplyDrop_C_ExecuteUbergraph_BP_MapObject_SupplyDrop");
static_assert(offsetof(BP_MapObject_SupplyDrop_C_ExecuteUbergraph_BP_MapObject_SupplyDrop, EntryPoint) == 0x000000, "Member 'BP_MapObject_SupplyDrop_C_ExecuteUbergraph_BP_MapObject_SupplyDrop::EntryPoint' has a wrong offset!");
static_assert(offsetof(BP_MapObject_SupplyDrop_C_ExecuteUbergraph_BP_MapObject_SupplyDrop, K2Node_Event_ConcreteModel) == 0x000008, "Member 'BP_MapObject_SupplyDrop_C_ExecuteUbergraph_BP_MapObject_SupplyDrop::K2Node_Event_ConcreteModel' has a wrong offset!");

// Function BP_MapObject_SupplyDrop.BP_MapObject_SupplyDrop_C.SetActiveFXInLocal
// 0x0018 (0x0018 - 0x0000)
struct BP_MapObject_SupplyDrop_C_SetActiveFXInLocal final
{
public:
	class UPalMapObjectConcreteModelBase*         ConcreteModel;                                     // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UPalMapObjectDeathPenaltyStorageModel*  K2Node_DynamicCast_AsPal_Map_Object_Death_Penalty_Storage_Model; // 0x0008(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0010(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsSameGuildInLocalPlayer_ReturnValue;     // 0x0011(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_MapObject_SupplyDrop_C_SetActiveFXInLocal) == 0x000008, "Wrong alignment on BP_MapObject_SupplyDrop_C_SetActiveFXInLocal");
static_assert(sizeof(BP_MapObject_SupplyDrop_C_SetActiveFXInLocal) == 0x000018, "Wrong size on BP_MapObject_SupplyDrop_C_SetActiveFXInLocal");
static_assert(offsetof(BP_MapObject_SupplyDrop_C_SetActiveFXInLocal, ConcreteModel) == 0x000000, "Member 'BP_MapObject_SupplyDrop_C_SetActiveFXInLocal::ConcreteModel' has a wrong offset!");
static_assert(offsetof(BP_MapObject_SupplyDrop_C_SetActiveFXInLocal, K2Node_DynamicCast_AsPal_Map_Object_Death_Penalty_Storage_Model) == 0x000008, "Member 'BP_MapObject_SupplyDrop_C_SetActiveFXInLocal::K2Node_DynamicCast_AsPal_Map_Object_Death_Penalty_Storage_Model' has a wrong offset!");
static_assert(offsetof(BP_MapObject_SupplyDrop_C_SetActiveFXInLocal, K2Node_DynamicCast_bSuccess) == 0x000010, "Member 'BP_MapObject_SupplyDrop_C_SetActiveFXInLocal::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(BP_MapObject_SupplyDrop_C_SetActiveFXInLocal, CallFunc_IsSameGuildInLocalPlayer_ReturnValue) == 0x000011, "Member 'BP_MapObject_SupplyDrop_C_SetActiveFXInLocal::CallFunc_IsSameGuildInLocalPlayer_ReturnValue' has a wrong offset!");

}

