#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_MapObject_SupplyDrop

#include "Basic.hpp"

#include "Pal_classes.hpp"
#include "Engine_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_MapObject_SupplyDrop.BP_MapObject_SupplyDrop_C
// 0x0088 (0x0470 - 0x03E8)
class ABP_MapObject_SupplyDrop_C final : public APalMapObject
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x03E8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UStaticMeshComponent*                   StaticMesh9;                                       // 0x03F0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   StaticMesh6;                                       // 0x03F8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   StaticMesh8;                                       // 0x0400(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   StaticMesh7;                                       // 0x0408(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   StaticMesh5;                                       // 0x0410(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   StaticMesh4;                                       // 0x0418(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   StaticMesh3;                                       // 0x0420(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   StaticMesh2;                                       // 0x0428(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   StaticMesh1;                                       // 0x0430(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   StaticMesh;                                        // 0x0438(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UNiagaraComponent*                      NS_MapObject_DroppedCharacter;                     // 0x0440(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UPalMapObjectItemChestParameterComponent* PalMapObjectItemChestParameter;                    // 0x0448(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UBoxComponent*                          CheckOverlapCollision;                             // 0x0450(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UBP_InteractableBox_C*                  BP_InteractableBox;                                // 0x0458(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   Mesh;                                              // 0x0460(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        Root;                                              // 0x0468(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	void BP_OnSetConcreteModel(class UPalMapObjectConcreteModelBase* ConcreteModel);
	void ExecuteUbergraph_BP_MapObject_SupplyDrop(int32 EntryPoint);
	void SetActiveFXInLocal(class UPalMapObjectConcreteModelBase* ConcreteModel);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_MapObject_SupplyDrop_C">();
	}
	static class ABP_MapObject_SupplyDrop_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_MapObject_SupplyDrop_C>();
	}
};
static_assert(alignof(ABP_MapObject_SupplyDrop_C) == 0x000008, "Wrong alignment on ABP_MapObject_SupplyDrop_C");
static_assert(sizeof(ABP_MapObject_SupplyDrop_C) == 0x000470, "Wrong size on ABP_MapObject_SupplyDrop_C");
static_assert(offsetof(ABP_MapObject_SupplyDrop_C, UberGraphFrame) == 0x0003E8, "Member 'ABP_MapObject_SupplyDrop_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(ABP_MapObject_SupplyDrop_C, StaticMesh9) == 0x0003F0, "Member 'ABP_MapObject_SupplyDrop_C::StaticMesh9' has a wrong offset!");
static_assert(offsetof(ABP_MapObject_SupplyDrop_C, StaticMesh6) == 0x0003F8, "Member 'ABP_MapObject_SupplyDrop_C::StaticMesh6' has a wrong offset!");
static_assert(offsetof(ABP_MapObject_SupplyDrop_C, StaticMesh8) == 0x000400, "Member 'ABP_MapObject_SupplyDrop_C::StaticMesh8' has a wrong offset!");
static_assert(offsetof(ABP_MapObject_SupplyDrop_C, StaticMesh7) == 0x000408, "Member 'ABP_MapObject_SupplyDrop_C::StaticMesh7' has a wrong offset!");
static_assert(offsetof(ABP_MapObject_SupplyDrop_C, StaticMesh5) == 0x000410, "Member 'ABP_MapObject_SupplyDrop_C::StaticMesh5' has a wrong offset!");
static_assert(offsetof(ABP_MapObject_SupplyDrop_C, StaticMesh4) == 0x000418, "Member 'ABP_MapObject_SupplyDrop_C::StaticMesh4' has a wrong offset!");
static_assert(offsetof(ABP_MapObject_SupplyDrop_C, StaticMesh3) == 0x000420, "Member 'ABP_MapObject_SupplyDrop_C::StaticMesh3' has a wrong offset!");
static_assert(offsetof(ABP_MapObject_SupplyDrop_C, StaticMesh2) == 0x000428, "Member 'ABP_MapObject_SupplyDrop_C::StaticMesh2' has a wrong offset!");
static_assert(offsetof(ABP_MapObject_SupplyDrop_C, StaticMesh1) == 0x000430, "Member 'ABP_MapObject_SupplyDrop_C::StaticMesh1' has a wrong offset!");
static_assert(offsetof(ABP_MapObject_SupplyDrop_C, StaticMesh) == 0x000438, "Member 'ABP_MapObject_SupplyDrop_C::StaticMesh' has a wrong offset!");
static_assert(offsetof(ABP_MapObject_SupplyDrop_C, NS_MapObject_DroppedCharacter) == 0x000440, "Member 'ABP_MapObject_SupplyDrop_C::NS_MapObject_DroppedCharacter' has a wrong offset!");
static_assert(offsetof(ABP_MapObject_SupplyDrop_C, PalMapObjectItemChestParameter) == 0x000448, "Member 'ABP_MapObject_SupplyDrop_C::PalMapObjectItemChestParameter' has a wrong offset!");
static_assert(offsetof(ABP_MapObject_SupplyDrop_C, CheckOverlapCollision) == 0x000450, "Member 'ABP_MapObject_SupplyDrop_C::CheckOverlapCollision' has a wrong offset!");
static_assert(offsetof(ABP_MapObject_SupplyDrop_C, BP_InteractableBox) == 0x000458, "Member 'ABP_MapObject_SupplyDrop_C::BP_InteractableBox' has a wrong offset!");
static_assert(offsetof(ABP_MapObject_SupplyDrop_C, Mesh) == 0x000460, "Member 'ABP_MapObject_SupplyDrop_C::Mesh' has a wrong offset!");
static_assert(offsetof(ABP_MapObject_SupplyDrop_C, Root) == 0x000468, "Member 'ABP_MapObject_SupplyDrop_C::Root' has a wrong offset!");

}

