#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_NPCAIController_Oilrig

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"


namespace SDK::Params
{

// Function BP_NPCAIController_Oilrig.BP_NPCAIController_Oilrig_C.ExecuteUbergraph_BP_NPCAIController_Oilrig
// 0x0090 (0x0090 - 0x0000)
struct BP_NPCAIController_Oilrig_C_ExecuteUbergraph_BP_NPCAIController_Oilrig final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         K2Node_Event_DeltaSeconds;                         // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UPalAIActionComponent*                  K2Node_DynamicCast_AsPal_AIAction_Component;       // 0x0008(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0010(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_60C8[0x7];                                     // 0x0011(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UPalOilrigManager*                      CallFunc_GetOilrigManager_ReturnValue;             // 0x0018(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UPawnAction*                            CallFunc_GetCurrentAction_BP_ReturnValue;          // 0x0020(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class APawn*                                  CallFunc_K2_GetPawn_ReturnValue;                   // 0x0028(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0030(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_60C9[0x7];                                     // 0x0031(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                CallFunc_K2_GetActorLocation_ReturnValue;          // 0x0038(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class APalOilrigController*                   CallFunc_FindNearestOilrigController_ReturnValue;  // 0x0050(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UBP_AIAction_NPC_RelaxBase_C*           K2Node_DynamicCast_AsBP_AIAction_NPC_Relax_Base;   // 0x0058(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_1;                     // 0x0060(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsCombatMode_ReturnValue;                 // 0x0061(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_60CA[0x6];                                     // 0x0062(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class APawn*                                  CallFunc_K2_GetPawn_ReturnValue_1;                 // 0x0068(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class APalCharacter*                          K2Node_DynamicCast_AsPal_Character;                // 0x0070(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_2;                     // 0x0078(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_60CB[0x7];                                     // 0x0079(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class APalPlayerCharacter*                    CallFunc_GetNearestFoundPlayer_ReturnValue;        // 0x0080(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class APawn*                                  K2Node_Event_PossessedPawn;                        // 0x0088(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_NPCAIController_Oilrig_C_ExecuteUbergraph_BP_NPCAIController_Oilrig) == 0x000008, "Wrong alignment on BP_NPCAIController_Oilrig_C_ExecuteUbergraph_BP_NPCAIController_Oilrig");
static_assert(sizeof(BP_NPCAIController_Oilrig_C_ExecuteUbergraph_BP_NPCAIController_Oilrig) == 0x000090, "Wrong size on BP_NPCAIController_Oilrig_C_ExecuteUbergraph_BP_NPCAIController_Oilrig");
static_assert(offsetof(BP_NPCAIController_Oilrig_C_ExecuteUbergraph_BP_NPCAIController_Oilrig, EntryPoint) == 0x000000, "Member 'BP_NPCAIController_Oilrig_C_ExecuteUbergraph_BP_NPCAIController_Oilrig::EntryPoint' has a wrong offset!");
static_assert(offsetof(BP_NPCAIController_Oilrig_C_ExecuteUbergraph_BP_NPCAIController_Oilrig, K2Node_Event_DeltaSeconds) == 0x000004, "Member 'BP_NPCAIController_Oilrig_C_ExecuteUbergraph_BP_NPCAIController_Oilrig::K2Node_Event_DeltaSeconds' has a wrong offset!");
static_assert(offsetof(BP_NPCAIController_Oilrig_C_ExecuteUbergraph_BP_NPCAIController_Oilrig, K2Node_DynamicCast_AsPal_AIAction_Component) == 0x000008, "Member 'BP_NPCAIController_Oilrig_C_ExecuteUbergraph_BP_NPCAIController_Oilrig::K2Node_DynamicCast_AsPal_AIAction_Component' has a wrong offset!");
static_assert(offsetof(BP_NPCAIController_Oilrig_C_ExecuteUbergraph_BP_NPCAIController_Oilrig, K2Node_DynamicCast_bSuccess) == 0x000010, "Member 'BP_NPCAIController_Oilrig_C_ExecuteUbergraph_BP_NPCAIController_Oilrig::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(BP_NPCAIController_Oilrig_C_ExecuteUbergraph_BP_NPCAIController_Oilrig, CallFunc_GetOilrigManager_ReturnValue) == 0x000018, "Member 'BP_NPCAIController_Oilrig_C_ExecuteUbergraph_BP_NPCAIController_Oilrig::CallFunc_GetOilrigManager_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_NPCAIController_Oilrig_C_ExecuteUbergraph_BP_NPCAIController_Oilrig, CallFunc_GetCurrentAction_BP_ReturnValue) == 0x000020, "Member 'BP_NPCAIController_Oilrig_C_ExecuteUbergraph_BP_NPCAIController_Oilrig::CallFunc_GetCurrentAction_BP_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_NPCAIController_Oilrig_C_ExecuteUbergraph_BP_NPCAIController_Oilrig, CallFunc_K2_GetPawn_ReturnValue) == 0x000028, "Member 'BP_NPCAIController_Oilrig_C_ExecuteUbergraph_BP_NPCAIController_Oilrig::CallFunc_K2_GetPawn_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_NPCAIController_Oilrig_C_ExecuteUbergraph_BP_NPCAIController_Oilrig, CallFunc_IsValid_ReturnValue) == 0x000030, "Member 'BP_NPCAIController_Oilrig_C_ExecuteUbergraph_BP_NPCAIController_Oilrig::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_NPCAIController_Oilrig_C_ExecuteUbergraph_BP_NPCAIController_Oilrig, CallFunc_K2_GetActorLocation_ReturnValue) == 0x000038, "Member 'BP_NPCAIController_Oilrig_C_ExecuteUbergraph_BP_NPCAIController_Oilrig::CallFunc_K2_GetActorLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_NPCAIController_Oilrig_C_ExecuteUbergraph_BP_NPCAIController_Oilrig, CallFunc_FindNearestOilrigController_ReturnValue) == 0x000050, "Member 'BP_NPCAIController_Oilrig_C_ExecuteUbergraph_BP_NPCAIController_Oilrig::CallFunc_FindNearestOilrigController_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_NPCAIController_Oilrig_C_ExecuteUbergraph_BP_NPCAIController_Oilrig, K2Node_DynamicCast_AsBP_AIAction_NPC_Relax_Base) == 0x000058, "Member 'BP_NPCAIController_Oilrig_C_ExecuteUbergraph_BP_NPCAIController_Oilrig::K2Node_DynamicCast_AsBP_AIAction_NPC_Relax_Base' has a wrong offset!");
static_assert(offsetof(BP_NPCAIController_Oilrig_C_ExecuteUbergraph_BP_NPCAIController_Oilrig, K2Node_DynamicCast_bSuccess_1) == 0x000060, "Member 'BP_NPCAIController_Oilrig_C_ExecuteUbergraph_BP_NPCAIController_Oilrig::K2Node_DynamicCast_bSuccess_1' has a wrong offset!");
static_assert(offsetof(BP_NPCAIController_Oilrig_C_ExecuteUbergraph_BP_NPCAIController_Oilrig, CallFunc_IsCombatMode_ReturnValue) == 0x000061, "Member 'BP_NPCAIController_Oilrig_C_ExecuteUbergraph_BP_NPCAIController_Oilrig::CallFunc_IsCombatMode_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_NPCAIController_Oilrig_C_ExecuteUbergraph_BP_NPCAIController_Oilrig, CallFunc_K2_GetPawn_ReturnValue_1) == 0x000068, "Member 'BP_NPCAIController_Oilrig_C_ExecuteUbergraph_BP_NPCAIController_Oilrig::CallFunc_K2_GetPawn_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_NPCAIController_Oilrig_C_ExecuteUbergraph_BP_NPCAIController_Oilrig, K2Node_DynamicCast_AsPal_Character) == 0x000070, "Member 'BP_NPCAIController_Oilrig_C_ExecuteUbergraph_BP_NPCAIController_Oilrig::K2Node_DynamicCast_AsPal_Character' has a wrong offset!");
static_assert(offsetof(BP_NPCAIController_Oilrig_C_ExecuteUbergraph_BP_NPCAIController_Oilrig, K2Node_DynamicCast_bSuccess_2) == 0x000078, "Member 'BP_NPCAIController_Oilrig_C_ExecuteUbergraph_BP_NPCAIController_Oilrig::K2Node_DynamicCast_bSuccess_2' has a wrong offset!");
static_assert(offsetof(BP_NPCAIController_Oilrig_C_ExecuteUbergraph_BP_NPCAIController_Oilrig, CallFunc_GetNearestFoundPlayer_ReturnValue) == 0x000080, "Member 'BP_NPCAIController_Oilrig_C_ExecuteUbergraph_BP_NPCAIController_Oilrig::CallFunc_GetNearestFoundPlayer_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_NPCAIController_Oilrig_C_ExecuteUbergraph_BP_NPCAIController_Oilrig, K2Node_Event_PossessedPawn) == 0x000088, "Member 'BP_NPCAIController_Oilrig_C_ExecuteUbergraph_BP_NPCAIController_Oilrig::K2Node_Event_PossessedPawn' has a wrong offset!");

// Function BP_NPCAIController_Oilrig.BP_NPCAIController_Oilrig_C.ReceivePossess
// 0x0008 (0x0008 - 0x0000)
struct BP_NPCAIController_Oilrig_C_ReceivePossess final
{
public:
	class APawn*                                  PossessedPawn;                                     // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_NPCAIController_Oilrig_C_ReceivePossess) == 0x000008, "Wrong alignment on BP_NPCAIController_Oilrig_C_ReceivePossess");
static_assert(sizeof(BP_NPCAIController_Oilrig_C_ReceivePossess) == 0x000008, "Wrong size on BP_NPCAIController_Oilrig_C_ReceivePossess");
static_assert(offsetof(BP_NPCAIController_Oilrig_C_ReceivePossess, PossessedPawn) == 0x000000, "Member 'BP_NPCAIController_Oilrig_C_ReceivePossess::PossessedPawn' has a wrong offset!");

// Function BP_NPCAIController_Oilrig.BP_NPCAIController_Oilrig_C.ReceiveTick
// 0x0004 (0x0004 - 0x0000)
struct BP_NPCAIController_Oilrig_C_ReceiveTick final
{
public:
	float                                         DeltaSeconds;                                      // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_NPCAIController_Oilrig_C_ReceiveTick) == 0x000004, "Wrong alignment on BP_NPCAIController_Oilrig_C_ReceiveTick");
static_assert(sizeof(BP_NPCAIController_Oilrig_C_ReceiveTick) == 0x000004, "Wrong size on BP_NPCAIController_Oilrig_C_ReceiveTick");
static_assert(offsetof(BP_NPCAIController_Oilrig_C_ReceiveTick, DeltaSeconds) == 0x000000, "Member 'BP_NPCAIController_Oilrig_C_ReceiveTick::DeltaSeconds' has a wrong offset!");

}

