#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_OilrigEmptyGoalBox

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_OilrigEmptyGoalBox.BP_OilrigEmptyGoalBox_C
// 0x0008 (0x0298 - 0x0290)
class ABP_OilrigEmptyGoalBox_C final : public AActor
{
public:
	class USkeletalMeshComponent*                 SkeletalMesh;                                      // 0x0290(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_OilrigEmptyGoalBox_C">();
	}
	static class ABP_OilrigEmptyGoalBox_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_OilrigEmptyGoalBox_C>();
	}
};
static_assert(alignof(ABP_OilrigEmptyGoalBox_C) == 0x000008, "Wrong alignment on ABP_OilrigEmptyGoalBox_C");
static_assert(sizeof(ABP_OilrigEmptyGoalBox_C) == 0x000298, "Wrong size on ABP_OilrigEmptyGoalBox_C");
static_assert(offsetof(ABP_OilrigEmptyGoalBox_C, SkeletalMesh) == 0x000290, "Member 'ABP_OilrigEmptyGoalBox_C::SkeletalMesh' has a wrong offset!");

}

