#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_OilrigNPCSpawner_Mono

#include "Basic.hpp"

#include "BP_OilrigNPCSpawnerBase_classes.hpp"
#include "Engine_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_OilrigNPCSpawner_Mono.BP_OilrigNPCSpawner_Mono_C
// 0x0008 (0x0320 - 0x0318)
class ABP_OilrigNPCSpawner_Mono_C final : public ABP_OilrigNPCSpawnerBase_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_BP_OilrigNPCSpawner_Mono_C;         // 0x0318(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_BP_OilrigNPCSpawner_Mono(int32 EntryPoint);
	void InitializeSpawnedCharacter(class UPalIndividualCharacterHandle* Handle);
	void On_Captured(class APalCharacter* SelfCharacter, class APalCharacter* Attacker);
	void On_Dead(const struct FPalDeadInfo& DeadInfo);
	void OnResetOilrig_BP();
	void ReceiveBeginPlay();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_OilrigNPCSpawner_Mono_C">();
	}
	static class ABP_OilrigNPCSpawner_Mono_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_OilrigNPCSpawner_Mono_C>();
	}
};
static_assert(alignof(ABP_OilrigNPCSpawner_Mono_C) == 0x000008, "Wrong alignment on ABP_OilrigNPCSpawner_Mono_C");
static_assert(sizeof(ABP_OilrigNPCSpawner_Mono_C) == 0x000320, "Wrong size on ABP_OilrigNPCSpawner_Mono_C");
static_assert(offsetof(ABP_OilrigNPCSpawner_Mono_C, UberGraphFrame_BP_OilrigNPCSpawner_Mono_C) == 0x000318, "Member 'ABP_OilrigNPCSpawner_Mono_C::UberGraphFrame_BP_OilrigNPCSpawner_Mono_C' has a wrong offset!");

}

