#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_OilrigExplosiveObjectBase

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"


namespace SDK::Params
{

// Function BP_OilrigExplosiveObjectBase.BP_OilrigExplosiveObjectBase_C.ExecuteUbergraph_BP_OilrigExplosiveObjectBase
// 0x00C0 (0x00C0 - 0x0000)
struct BP_OilrigExplosiveObjectBase_C_ExecuteUbergraph_BP_OilrigExplosiveObjectBase final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate;              // 0x0004(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_524A[0x4];                                     // 0x0014(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UPalMapObjectManager*                   CallFunc_GetMapObjectManager_ReturnValue;          // 0x0018(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_K2_GetActorLocation_ReturnValue;          // 0x0020(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_GetComponentBounds_Origin;                // 0x0038(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_GetComponentBounds_BoxExtent;             // 0x0050(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_GetComponentBounds_SphereRadius;          // 0x0068(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_524B[0x4];                                     // 0x006C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_Multiply_DoubleDouble_ReturnValue;        // 0x0070(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FBoxSphereBounds                       CallFunc_MakeBoxSphereBounds_ReturnValue;          // 0x0078(0x0038)(ZeroConstructor, IsPlainOldData, NoDestructor)
	double                                        CallFunc_Multiply_DoubleDouble_A_ImplicitCast;     // 0x00B0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_MakeBoxSphereBounds_SphereRadius_ImplicitCast; // 0x00B8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_OilrigExplosiveObjectBase_C_ExecuteUbergraph_BP_OilrigExplosiveObjectBase) == 0x000008, "Wrong alignment on BP_OilrigExplosiveObjectBase_C_ExecuteUbergraph_BP_OilrigExplosiveObjectBase");
static_assert(sizeof(BP_OilrigExplosiveObjectBase_C_ExecuteUbergraph_BP_OilrigExplosiveObjectBase) == 0x0000C0, "Wrong size on BP_OilrigExplosiveObjectBase_C_ExecuteUbergraph_BP_OilrigExplosiveObjectBase");
static_assert(offsetof(BP_OilrigExplosiveObjectBase_C_ExecuteUbergraph_BP_OilrigExplosiveObjectBase, EntryPoint) == 0x000000, "Member 'BP_OilrigExplosiveObjectBase_C_ExecuteUbergraph_BP_OilrigExplosiveObjectBase::EntryPoint' has a wrong offset!");
static_assert(offsetof(BP_OilrigExplosiveObjectBase_C_ExecuteUbergraph_BP_OilrigExplosiveObjectBase, K2Node_CreateDelegate_OutputDelegate) == 0x000004, "Member 'BP_OilrigExplosiveObjectBase_C_ExecuteUbergraph_BP_OilrigExplosiveObjectBase::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(BP_OilrigExplosiveObjectBase_C_ExecuteUbergraph_BP_OilrigExplosiveObjectBase, CallFunc_GetMapObjectManager_ReturnValue) == 0x000018, "Member 'BP_OilrigExplosiveObjectBase_C_ExecuteUbergraph_BP_OilrigExplosiveObjectBase::CallFunc_GetMapObjectManager_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_OilrigExplosiveObjectBase_C_ExecuteUbergraph_BP_OilrigExplosiveObjectBase, CallFunc_K2_GetActorLocation_ReturnValue) == 0x000020, "Member 'BP_OilrigExplosiveObjectBase_C_ExecuteUbergraph_BP_OilrigExplosiveObjectBase::CallFunc_K2_GetActorLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_OilrigExplosiveObjectBase_C_ExecuteUbergraph_BP_OilrigExplosiveObjectBase, CallFunc_GetComponentBounds_Origin) == 0x000038, "Member 'BP_OilrigExplosiveObjectBase_C_ExecuteUbergraph_BP_OilrigExplosiveObjectBase::CallFunc_GetComponentBounds_Origin' has a wrong offset!");
static_assert(offsetof(BP_OilrigExplosiveObjectBase_C_ExecuteUbergraph_BP_OilrigExplosiveObjectBase, CallFunc_GetComponentBounds_BoxExtent) == 0x000050, "Member 'BP_OilrigExplosiveObjectBase_C_ExecuteUbergraph_BP_OilrigExplosiveObjectBase::CallFunc_GetComponentBounds_BoxExtent' has a wrong offset!");
static_assert(offsetof(BP_OilrigExplosiveObjectBase_C_ExecuteUbergraph_BP_OilrigExplosiveObjectBase, CallFunc_GetComponentBounds_SphereRadius) == 0x000068, "Member 'BP_OilrigExplosiveObjectBase_C_ExecuteUbergraph_BP_OilrigExplosiveObjectBase::CallFunc_GetComponentBounds_SphereRadius' has a wrong offset!");
static_assert(offsetof(BP_OilrigExplosiveObjectBase_C_ExecuteUbergraph_BP_OilrigExplosiveObjectBase, CallFunc_Multiply_DoubleDouble_ReturnValue) == 0x000070, "Member 'BP_OilrigExplosiveObjectBase_C_ExecuteUbergraph_BP_OilrigExplosiveObjectBase::CallFunc_Multiply_DoubleDouble_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_OilrigExplosiveObjectBase_C_ExecuteUbergraph_BP_OilrigExplosiveObjectBase, CallFunc_MakeBoxSphereBounds_ReturnValue) == 0x000078, "Member 'BP_OilrigExplosiveObjectBase_C_ExecuteUbergraph_BP_OilrigExplosiveObjectBase::CallFunc_MakeBoxSphereBounds_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_OilrigExplosiveObjectBase_C_ExecuteUbergraph_BP_OilrigExplosiveObjectBase, CallFunc_Multiply_DoubleDouble_A_ImplicitCast) == 0x0000B0, "Member 'BP_OilrigExplosiveObjectBase_C_ExecuteUbergraph_BP_OilrigExplosiveObjectBase::CallFunc_Multiply_DoubleDouble_A_ImplicitCast' has a wrong offset!");
static_assert(offsetof(BP_OilrigExplosiveObjectBase_C_ExecuteUbergraph_BP_OilrigExplosiveObjectBase, CallFunc_MakeBoxSphereBounds_SphereRadius_ImplicitCast) == 0x0000B8, "Member 'BP_OilrigExplosiveObjectBase_C_ExecuteUbergraph_BP_OilrigExplosiveObjectBase::CallFunc_MakeBoxSphereBounds_SphereRadius_ImplicitCast' has a wrong offset!");

}

