#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_OilrigExplosiveObject_Barrel

#include "Basic.hpp"

#include "BP_OilrigExplosiveObjectBase_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_OilrigExplosiveObject_Barrel.BP_OilrigExplosiveObject_Barrel_C
// 0x0000 (0x02D8 - 0x02D8)
class ABP_OilrigExplosiveObject_Barrel_C final : public ABP_OilrigExplosiveObjectBase_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_OilrigExplosiveObject_Barrel_C">();
	}
	static class ABP_OilrigExplosiveObject_Barrel_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_OilrigExplosiveObject_Barrel_C>();
	}
};
static_assert(alignof(ABP_OilrigExplosiveObject_Barrel_C) == 0x000008, "Wrong alignment on ABP_OilrigExplosiveObject_Barrel_C");
static_assert(sizeof(ABP_OilrigExplosiveObject_Barrel_C) == 0x0002D8, "Wrong size on ABP_OilrigExplosiveObject_Barrel_C");

}

