#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_SkillEffect_Unique_FireKirin_Tackle

#include "Basic.hpp"

#include "BP_SkillEffect_Unique_FireKirin_Tackle_classes.hpp"
#include "BP_SkillEffect_Unique_FireKirin_Tackle_parameters.hpp"


namespace SDK
{

// Function BP_SkillEffect_Unique_FireKirin_Tackle.BP_SkillEffect_Unique_FireKirin_Tackle_C.ExecuteUbergraph_BP_SkillEffect_Unique_FireKirin_Tackle
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_SkillEffect_Unique_FireKirin_Tackle_C::ExecuteUbergraph_BP_SkillEffect_Unique_FireKirin_Tackle(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SkillEffect_Unique_FireKirin_Tackle_C", "ExecuteUbergraph_BP_SkillEffect_Unique_FireKirin_Tackle");

	Params::BP_SkillEffect_Unique_FireKirin_Tackle_C_ExecuteUbergraph_BP_SkillEffect_Unique_FireKirin_Tackle Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_SkillEffect_Unique_FireKirin_Tackle.BP_SkillEffect_Unique_FireKirin_Tackle_C.FadeOutEffect
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// double                                  DeltaSecond                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_SkillEffect_Unique_FireKirin_Tackle_C::FadeOutEffect(double DeltaSecond)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SkillEffect_Unique_FireKirin_Tackle_C", "FadeOutEffect");

	Params::BP_SkillEffect_Unique_FireKirin_Tackle_C_FadeOutEffect Parms{};

	Parms.DeltaSecond = DeltaSecond;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_SkillEffect_Unique_FireKirin_Tackle.BP_SkillEffect_Unique_FireKirin_Tackle_C.GetCurrentDistance
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// double                                  Distance                                               (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_SkillEffect_Unique_FireKirin_Tackle_C::GetCurrentDistance(double* Distance)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SkillEffect_Unique_FireKirin_Tackle_C", "GetCurrentDistance");

	Params::BP_SkillEffect_Unique_FireKirin_Tackle_C_GetCurrentDistance Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Distance != nullptr)
		*Distance = Parms.Distance;
}


// Function BP_SkillEffect_Unique_FireKirin_Tackle.BP_SkillEffect_Unique_FireKirin_Tackle_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_SkillEffect_Unique_FireKirin_Tackle_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SkillEffect_Unique_FireKirin_Tackle_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_SkillEffect_Unique_FireKirin_Tackle.BP_SkillEffect_Unique_FireKirin_Tackle_C.ReceiveTick
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_SkillEffect_Unique_FireKirin_Tackle_C::ReceiveTick(float DeltaSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SkillEffect_Unique_FireKirin_Tackle_C", "ReceiveTick");

	Params::BP_SkillEffect_Unique_FireKirin_Tackle_C_ReceiveTick Parms{};

	Parms.DeltaSeconds = DeltaSeconds;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_SkillEffect_Unique_FireKirin_Tackle.BP_SkillEffect_Unique_FireKirin_Tackle_C.SetupBoxCollisions
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void ABP_SkillEffect_Unique_FireKirin_Tackle_C::SetupBoxCollisions()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SkillEffect_Unique_FireKirin_Tackle_C", "SetupBoxCollisions");

	UObject::ProcessEvent(Func, nullptr);
}

}

