#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_SkillEffect_Unique_FireKirin_Tackle

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "BP_SkillEffectBase_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_SkillEffect_Unique_FireKirin_Tackle.BP_SkillEffect_Unique_FireKirin_Tackle_C
// 0x0150 (0x0510 - 0x03C0)
class ABP_SkillEffect_Unique_FireKirin_Tackle_C final : public ABP_SkillEffectBase_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_BP_SkillEffect_Unique_FireKirin_Tackle_C; // 0x03C0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UBoxComponent*                          BoxCollision30;                                    // 0x03C8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UBoxComponent*                          BoxCollision29;                                    // 0x03D0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UBoxComponent*                          BoxCollision28;                                    // 0x03D8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UBoxComponent*                          BoxCollision27;                                    // 0x03E0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UBoxComponent*                          BoxCollision26;                                    // 0x03E8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UBoxComponent*                          BoxCollision25;                                    // 0x03F0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UBoxComponent*                          BoxCollision24;                                    // 0x03F8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UBoxComponent*                          BoxCollision23;                                    // 0x0400(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UBoxComponent*                          BoxCollision22;                                    // 0x0408(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UBoxComponent*                          BoxCollision21;                                    // 0x0410(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UBoxComponent*                          BoxCollision20;                                    // 0x0418(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UBoxComponent*                          BoxCollision19;                                    // 0x0420(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UBoxComponent*                          BoxCollision18;                                    // 0x0428(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UBoxComponent*                          BoxCollision17;                                    // 0x0430(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UBoxComponent*                          BoxCollision16;                                    // 0x0438(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UBoxComponent*                          BoxCollision15;                                    // 0x0440(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UBoxComponent*                          BoxCollision14;                                    // 0x0448(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UBoxComponent*                          BoxCollision13;                                    // 0x0450(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UBoxComponent*                          BoxCollision12;                                    // 0x0458(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UBoxComponent*                          BoxCollision11;                                    // 0x0460(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UBoxComponent*                          BoxCollision10;                                    // 0x0468(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UBoxComponent*                          BoxCollision9;                                     // 0x0470(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UBoxComponent*                          BoxCollision8;                                     // 0x0478(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UBoxComponent*                          BoxCollision7;                                     // 0x0480(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UBoxComponent*                          BoxCollision6;                                     // 0x0488(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UBoxComponent*                          BoxCollision5;                                     // 0x0490(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UBoxComponent*                          BoxCollision4;                                     // 0x0498(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UBoxComponent*                          BoxCollision3;                                     // 0x04A0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UBoxComponent*                          BoxCollision2;                                     // 0x04A8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UBoxComponent*                          BoxCollision1;                                     // 0x04B0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UBoxComponent*                          BoxCollision;                                      // 0x04B8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	TArray<class UBoxComponent*>                  BoxCollisions;                                     // 0x04C0(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance, ContainsInstancedReference)
	int32                                         CurrentIndex;                                      // 0x04D0(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3C4A[0x4];                                     // 0x04D4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        BoxDistance;                                       // 0x04D8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                BoxExtent;                                         // 0x04E0(0x0018)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                PreBoxLocation;                                    // 0x04F8(0x0018)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_BP_SkillEffect_Unique_FireKirin_Tackle(int32 EntryPoint);
	void FadeOutEffect(double DeltaSecond);
	void GetCurrentDistance(double* Distance);
	void ReceiveBeginPlay();
	void ReceiveTick(float DeltaSeconds);
	void SetupBoxCollisions();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_SkillEffect_Unique_FireKirin_Tackle_C">();
	}
	static class ABP_SkillEffect_Unique_FireKirin_Tackle_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_SkillEffect_Unique_FireKirin_Tackle_C>();
	}
};
static_assert(alignof(ABP_SkillEffect_Unique_FireKirin_Tackle_C) == 0x000008, "Wrong alignment on ABP_SkillEffect_Unique_FireKirin_Tackle_C");
static_assert(sizeof(ABP_SkillEffect_Unique_FireKirin_Tackle_C) == 0x000510, "Wrong size on ABP_SkillEffect_Unique_FireKirin_Tackle_C");
static_assert(offsetof(ABP_SkillEffect_Unique_FireKirin_Tackle_C, UberGraphFrame_BP_SkillEffect_Unique_FireKirin_Tackle_C) == 0x0003C0, "Member 'ABP_SkillEffect_Unique_FireKirin_Tackle_C::UberGraphFrame_BP_SkillEffect_Unique_FireKirin_Tackle_C' has a wrong offset!");
static_assert(offsetof(ABP_SkillEffect_Unique_FireKirin_Tackle_C, BoxCollision30) == 0x0003C8, "Member 'ABP_SkillEffect_Unique_FireKirin_Tackle_C::BoxCollision30' has a wrong offset!");
static_assert(offsetof(ABP_SkillEffect_Unique_FireKirin_Tackle_C, BoxCollision29) == 0x0003D0, "Member 'ABP_SkillEffect_Unique_FireKirin_Tackle_C::BoxCollision29' has a wrong offset!");
static_assert(offsetof(ABP_SkillEffect_Unique_FireKirin_Tackle_C, BoxCollision28) == 0x0003D8, "Member 'ABP_SkillEffect_Unique_FireKirin_Tackle_C::BoxCollision28' has a wrong offset!");
static_assert(offsetof(ABP_SkillEffect_Unique_FireKirin_Tackle_C, BoxCollision27) == 0x0003E0, "Member 'ABP_SkillEffect_Unique_FireKirin_Tackle_C::BoxCollision27' has a wrong offset!");
static_assert(offsetof(ABP_SkillEffect_Unique_FireKirin_Tackle_C, BoxCollision26) == 0x0003E8, "Member 'ABP_SkillEffect_Unique_FireKirin_Tackle_C::BoxCollision26' has a wrong offset!");
static_assert(offsetof(ABP_SkillEffect_Unique_FireKirin_Tackle_C, BoxCollision25) == 0x0003F0, "Member 'ABP_SkillEffect_Unique_FireKirin_Tackle_C::BoxCollision25' has a wrong offset!");
static_assert(offsetof(ABP_SkillEffect_Unique_FireKirin_Tackle_C, BoxCollision24) == 0x0003F8, "Member 'ABP_SkillEffect_Unique_FireKirin_Tackle_C::BoxCollision24' has a wrong offset!");
static_assert(offsetof(ABP_SkillEffect_Unique_FireKirin_Tackle_C, BoxCollision23) == 0x000400, "Member 'ABP_SkillEffect_Unique_FireKirin_Tackle_C::BoxCollision23' has a wrong offset!");
static_assert(offsetof(ABP_SkillEffect_Unique_FireKirin_Tackle_C, BoxCollision22) == 0x000408, "Member 'ABP_SkillEffect_Unique_FireKirin_Tackle_C::BoxCollision22' has a wrong offset!");
static_assert(offsetof(ABP_SkillEffect_Unique_FireKirin_Tackle_C, BoxCollision21) == 0x000410, "Member 'ABP_SkillEffect_Unique_FireKirin_Tackle_C::BoxCollision21' has a wrong offset!");
static_assert(offsetof(ABP_SkillEffect_Unique_FireKirin_Tackle_C, BoxCollision20) == 0x000418, "Member 'ABP_SkillEffect_Unique_FireKirin_Tackle_C::BoxCollision20' has a wrong offset!");
static_assert(offsetof(ABP_SkillEffect_Unique_FireKirin_Tackle_C, BoxCollision19) == 0x000420, "Member 'ABP_SkillEffect_Unique_FireKirin_Tackle_C::BoxCollision19' has a wrong offset!");
static_assert(offsetof(ABP_SkillEffect_Unique_FireKirin_Tackle_C, BoxCollision18) == 0x000428, "Member 'ABP_SkillEffect_Unique_FireKirin_Tackle_C::BoxCollision18' has a wrong offset!");
static_assert(offsetof(ABP_SkillEffect_Unique_FireKirin_Tackle_C, BoxCollision17) == 0x000430, "Member 'ABP_SkillEffect_Unique_FireKirin_Tackle_C::BoxCollision17' has a wrong offset!");
static_assert(offsetof(ABP_SkillEffect_Unique_FireKirin_Tackle_C, BoxCollision16) == 0x000438, "Member 'ABP_SkillEffect_Unique_FireKirin_Tackle_C::BoxCollision16' has a wrong offset!");
static_assert(offsetof(ABP_SkillEffect_Unique_FireKirin_Tackle_C, BoxCollision15) == 0x000440, "Member 'ABP_SkillEffect_Unique_FireKirin_Tackle_C::BoxCollision15' has a wrong offset!");
static_assert(offsetof(ABP_SkillEffect_Unique_FireKirin_Tackle_C, BoxCollision14) == 0x000448, "Member 'ABP_SkillEffect_Unique_FireKirin_Tackle_C::BoxCollision14' has a wrong offset!");
static_assert(offsetof(ABP_SkillEffect_Unique_FireKirin_Tackle_C, BoxCollision13) == 0x000450, "Member 'ABP_SkillEffect_Unique_FireKirin_Tackle_C::BoxCollision13' has a wrong offset!");
static_assert(offsetof(ABP_SkillEffect_Unique_FireKirin_Tackle_C, BoxCollision12) == 0x000458, "Member 'ABP_SkillEffect_Unique_FireKirin_Tackle_C::BoxCollision12' has a wrong offset!");
static_assert(offsetof(ABP_SkillEffect_Unique_FireKirin_Tackle_C, BoxCollision11) == 0x000460, "Member 'ABP_SkillEffect_Unique_FireKirin_Tackle_C::BoxCollision11' has a wrong offset!");
static_assert(offsetof(ABP_SkillEffect_Unique_FireKirin_Tackle_C, BoxCollision10) == 0x000468, "Member 'ABP_SkillEffect_Unique_FireKirin_Tackle_C::BoxCollision10' has a wrong offset!");
static_assert(offsetof(ABP_SkillEffect_Unique_FireKirin_Tackle_C, BoxCollision9) == 0x000470, "Member 'ABP_SkillEffect_Unique_FireKirin_Tackle_C::BoxCollision9' has a wrong offset!");
static_assert(offsetof(ABP_SkillEffect_Unique_FireKirin_Tackle_C, BoxCollision8) == 0x000478, "Member 'ABP_SkillEffect_Unique_FireKirin_Tackle_C::BoxCollision8' has a wrong offset!");
static_assert(offsetof(ABP_SkillEffect_Unique_FireKirin_Tackle_C, BoxCollision7) == 0x000480, "Member 'ABP_SkillEffect_Unique_FireKirin_Tackle_C::BoxCollision7' has a wrong offset!");
static_assert(offsetof(ABP_SkillEffect_Unique_FireKirin_Tackle_C, BoxCollision6) == 0x000488, "Member 'ABP_SkillEffect_Unique_FireKirin_Tackle_C::BoxCollision6' has a wrong offset!");
static_assert(offsetof(ABP_SkillEffect_Unique_FireKirin_Tackle_C, BoxCollision5) == 0x000490, "Member 'ABP_SkillEffect_Unique_FireKirin_Tackle_C::BoxCollision5' has a wrong offset!");
static_assert(offsetof(ABP_SkillEffect_Unique_FireKirin_Tackle_C, BoxCollision4) == 0x000498, "Member 'ABP_SkillEffect_Unique_FireKirin_Tackle_C::BoxCollision4' has a wrong offset!");
static_assert(offsetof(ABP_SkillEffect_Unique_FireKirin_Tackle_C, BoxCollision3) == 0x0004A0, "Member 'ABP_SkillEffect_Unique_FireKirin_Tackle_C::BoxCollision3' has a wrong offset!");
static_assert(offsetof(ABP_SkillEffect_Unique_FireKirin_Tackle_C, BoxCollision2) == 0x0004A8, "Member 'ABP_SkillEffect_Unique_FireKirin_Tackle_C::BoxCollision2' has a wrong offset!");
static_assert(offsetof(ABP_SkillEffect_Unique_FireKirin_Tackle_C, BoxCollision1) == 0x0004B0, "Member 'ABP_SkillEffect_Unique_FireKirin_Tackle_C::BoxCollision1' has a wrong offset!");
static_assert(offsetof(ABP_SkillEffect_Unique_FireKirin_Tackle_C, BoxCollision) == 0x0004B8, "Member 'ABP_SkillEffect_Unique_FireKirin_Tackle_C::BoxCollision' has a wrong offset!");
static_assert(offsetof(ABP_SkillEffect_Unique_FireKirin_Tackle_C, BoxCollisions) == 0x0004C0, "Member 'ABP_SkillEffect_Unique_FireKirin_Tackle_C::BoxCollisions' has a wrong offset!");
static_assert(offsetof(ABP_SkillEffect_Unique_FireKirin_Tackle_C, CurrentIndex) == 0x0004D0, "Member 'ABP_SkillEffect_Unique_FireKirin_Tackle_C::CurrentIndex' has a wrong offset!");
static_assert(offsetof(ABP_SkillEffect_Unique_FireKirin_Tackle_C, BoxDistance) == 0x0004D8, "Member 'ABP_SkillEffect_Unique_FireKirin_Tackle_C::BoxDistance' has a wrong offset!");
static_assert(offsetof(ABP_SkillEffect_Unique_FireKirin_Tackle_C, BoxExtent) == 0x0004E0, "Member 'ABP_SkillEffect_Unique_FireKirin_Tackle_C::BoxExtent' has a wrong offset!");
static_assert(offsetof(ABP_SkillEffect_Unique_FireKirin_Tackle_C, PreBoxLocation) == 0x0004F8, "Member 'ABP_SkillEffect_Unique_FireKirin_Tackle_C::PreBoxLocation' has a wrong offset!");

}

