#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_SupplySpawner_Forest01

#include "Basic.hpp"

#include "BP_SupplySpawnerBase_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_SupplySpawner_Forest01.BP_SupplySpawner_Forest01_C
// 0x0000 (0x0308 - 0x0308)
class ABP_SupplySpawner_Forest01_C final : public ABP_SupplySpawnerBase_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_SupplySpawner_Forest01_C">();
	}
	static class ABP_SupplySpawner_Forest01_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_SupplySpawner_Forest01_C>();
	}
};
static_assert(alignof(ABP_SupplySpawner_Forest01_C) == 0x000008, "Wrong alignment on ABP_SupplySpawner_Forest01_C");
static_assert(sizeof(ABP_SupplySpawner_Forest01_C) == 0x000308, "Wrong size on ABP_SupplySpawner_Forest01_C");

}

