#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_SkillEffect_Unique_ElecPanda_GatlingAttack_Bullet

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "BP_SkillEffectBase_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_SkillEffect_Unique_ElecPanda_GatlingAttack_Bullet.BP_SkillEffect_Unique_ElecPanda_GatlingAttack_Bullet_C
// 0x0020 (0x03E0 - 0x03C0)
class ABP_SkillEffect_Unique_ElecPanda_GatlingAttack_Bullet_C final : public ABP_SkillEffectBase_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_BP_SkillEffect_Unique_ElecPanda_GatlingAttack_Bullet_C; // 0x03C0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UCapsuleComponent*                      Capsule;                                           // 0x03C8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   StaticMesh;                                        // 0x03D0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UProjectileMovementComponent*           ProjectileMovement;                                // 0x03D8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	void BndEvt__BP_SkillEffect_Unique_ElecPanda_GatlingAttack_Bullet_MovementSphereRoot_K2Node_ComponentBoundEvent_0_ComponentHitSignature__DelegateSignature(class UPrimitiveComponent* HitComponent, class AActor* OtherActor, class UPrimitiveComponent* OtherComp, const struct FVector& NormalImpulse, const struct FHitResult& Hit);
	void ExecuteUbergraph_BP_SkillEffect_Unique_ElecPanda_GatlingAttack_Bullet(int32 EntryPoint);
	void OnHitDelegate_____(class UPrimitiveComponent* MyHitComponent, class AActor* OtherHitActor, class UPrimitiveComponent* OtherHitComponent, const TArray<int32>& FoliageIndex, const struct FVector& HitLocation, int32 HitCount);
	void ReceiveBeginPlay();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_SkillEffect_Unique_ElecPanda_GatlingAttack_Bullet_C">();
	}
	static class ABP_SkillEffect_Unique_ElecPanda_GatlingAttack_Bullet_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_SkillEffect_Unique_ElecPanda_GatlingAttack_Bullet_C>();
	}
};
static_assert(alignof(ABP_SkillEffect_Unique_ElecPanda_GatlingAttack_Bullet_C) == 0x000008, "Wrong alignment on ABP_SkillEffect_Unique_ElecPanda_GatlingAttack_Bullet_C");
static_assert(sizeof(ABP_SkillEffect_Unique_ElecPanda_GatlingAttack_Bullet_C) == 0x0003E0, "Wrong size on ABP_SkillEffect_Unique_ElecPanda_GatlingAttack_Bullet_C");
static_assert(offsetof(ABP_SkillEffect_Unique_ElecPanda_GatlingAttack_Bullet_C, UberGraphFrame_BP_SkillEffect_Unique_ElecPanda_GatlingAttack_Bullet_C) == 0x0003C0, "Member 'ABP_SkillEffect_Unique_ElecPanda_GatlingAttack_Bullet_C::UberGraphFrame_BP_SkillEffect_Unique_ElecPanda_GatlingAttack_Bullet_C' has a wrong offset!");
static_assert(offsetof(ABP_SkillEffect_Unique_ElecPanda_GatlingAttack_Bullet_C, Capsule) == 0x0003C8, "Member 'ABP_SkillEffect_Unique_ElecPanda_GatlingAttack_Bullet_C::Capsule' has a wrong offset!");
static_assert(offsetof(ABP_SkillEffect_Unique_ElecPanda_GatlingAttack_Bullet_C, StaticMesh) == 0x0003D0, "Member 'ABP_SkillEffect_Unique_ElecPanda_GatlingAttack_Bullet_C::StaticMesh' has a wrong offset!");
static_assert(offsetof(ABP_SkillEffect_Unique_ElecPanda_GatlingAttack_Bullet_C, ProjectileMovement) == 0x0003D8, "Member 'ABP_SkillEffect_Unique_ElecPanda_GatlingAttack_Bullet_C::ProjectileMovement' has a wrong offset!");

}

