#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_SoundSlot_Weapon_FlameThrower

#include "Basic.hpp"

#include "BP_SoundSlot_Weapon_Minigun_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_SoundSlot_Weapon_FlameThrower.BP_SoundSlot_Weapon_FlameThrower_C
// 0x0000 (0x00D0 - 0x00D0)
class UBP_SoundSlot_Weapon_FlameThrower_C final : public UBP_SoundSlot_Weapon_Minigun_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_SoundSlot_Weapon_FlameThrower_C">();
	}
	static class UBP_SoundSlot_Weapon_FlameThrower_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_SoundSlot_Weapon_FlameThrower_C>();
	}
};
static_assert(alignof(UBP_SoundSlot_Weapon_FlameThrower_C) == 0x000008, "Wrong alignment on UBP_SoundSlot_Weapon_FlameThrower_C");
static_assert(sizeof(UBP_SoundSlot_Weapon_FlameThrower_C) == 0x0000D0, "Wrong size on UBP_SoundSlot_Weapon_FlameThrower_C");

}

