#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_UniqueSkillModule_Tackle_FireKirin

#include "Basic.hpp"

#include "BP_UniqueSkillModule_Tackle_FireKirin_classes.hpp"
#include "BP_UniqueSkillModule_Tackle_FireKirin_parameters.hpp"


namespace SDK
{

// Function BP_UniqueSkillModule_Tackle_FireKirin.BP_UniqueSkillModule_Tackle_FireKirin_C.ExecuteUbergraph_BP_UniqueSkillModule_Tackle_FireKirin
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_UniqueSkillModule_Tackle_FireKirin_C::ExecuteUbergraph_BP_UniqueSkillModule_Tackle_FireKirin(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_UniqueSkillModule_Tackle_FireKirin_C", "ExecuteUbergraph_BP_UniqueSkillModule_Tackle_FireKirin");

	Params::BP_UniqueSkillModule_Tackle_FireKirin_C_ExecuteUbergraph_BP_UniqueSkillModule_Tackle_FireKirin Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_UniqueSkillModule_Tackle_FireKirin.BP_UniqueSkillModule_Tackle_FireKirin_C.OnEndAttack
// (BlueprintCallable, BlueprintEvent)

void UBP_UniqueSkillModule_Tackle_FireKirin_C::OnEndAttack()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_UniqueSkillModule_Tackle_FireKirin_C", "OnEndAttack");

	UObject::ProcessEvent(Func, nullptr);
}

}

