#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_UniqueRideWeapon_RapidBase

#include "Basic.hpp"

#include "Pal_classes.hpp"
#include "Engine_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_UniqueRideWeapon_RapidBase.BP_UniqueRideWeapon_RapidBase_C
// 0x0018 (0x05A8 - 0x0590)
class ABP_UniqueRideWeapon_RapidBase_C : public APalUniqueRideWeaponBase
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0590(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x0598(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	struct FTimerHandle                           ShootHandle;                                       // 0x05A0(0x0008)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_BP_UniqueRideWeapon_RapidBase(int32 EntryPoint);
	void GetShootInterval(double* Time);
	void OnPullTrigger();
	void OnReleaseTrigger();
	void ShootBulletBP();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_UniqueRideWeapon_RapidBase_C">();
	}
	static class ABP_UniqueRideWeapon_RapidBase_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_UniqueRideWeapon_RapidBase_C>();
	}
};
static_assert(alignof(ABP_UniqueRideWeapon_RapidBase_C) == 0x000008, "Wrong alignment on ABP_UniqueRideWeapon_RapidBase_C");
static_assert(sizeof(ABP_UniqueRideWeapon_RapidBase_C) == 0x0005A8, "Wrong size on ABP_UniqueRideWeapon_RapidBase_C");
static_assert(offsetof(ABP_UniqueRideWeapon_RapidBase_C, UberGraphFrame) == 0x000590, "Member 'ABP_UniqueRideWeapon_RapidBase_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(ABP_UniqueRideWeapon_RapidBase_C, DefaultSceneRoot) == 0x000598, "Member 'ABP_UniqueRideWeapon_RapidBase_C::DefaultSceneRoot' has a wrong offset!");
static_assert(offsetof(ABP_UniqueRideWeapon_RapidBase_C, ShootHandle) == 0x0005A0, "Member 'ABP_UniqueRideWeapon_RapidBase_C::ShootHandle' has a wrong offset!");

}

