#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_UniqueSkillModule_Tackle_FireKirin

#include "Basic.hpp"


namespace SDK::Params
{

// Function BP_UniqueSkillModule_Tackle_FireKirin.BP_UniqueSkillModule_Tackle_FireKirin_C.ExecuteUbergraph_BP_UniqueSkillModule_Tackle_FireKirin
// 0x0004 (0x0004 - 0x0000)
struct BP_UniqueSkillModule_Tackle_FireKirin_C_ExecuteUbergraph_BP_UniqueSkillModule_Tackle_FireKirin final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_UniqueSkillModule_Tackle_FireKirin_C_ExecuteUbergraph_BP_UniqueSkillModule_Tackle_FireKirin) == 0x000004, "Wrong alignment on BP_UniqueSkillModule_Tackle_FireKirin_C_ExecuteUbergraph_BP_UniqueSkillModule_Tackle_FireKirin");
static_assert(sizeof(BP_UniqueSkillModule_Tackle_FireKirin_C_ExecuteUbergraph_BP_UniqueSkillModule_Tackle_FireKirin) == 0x000004, "Wrong size on BP_UniqueSkillModule_Tackle_FireKirin_C_ExecuteUbergraph_BP_UniqueSkillModule_Tackle_FireKirin");
static_assert(offsetof(BP_UniqueSkillModule_Tackle_FireKirin_C_ExecuteUbergraph_BP_UniqueSkillModule_Tackle_FireKirin, EntryPoint) == 0x000000, "Member 'BP_UniqueSkillModule_Tackle_FireKirin_C_ExecuteUbergraph_BP_UniqueSkillModule_Tackle_FireKirin::EntryPoint' has a wrong offset!");

}

