#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_UniqueSkillModule_Tackle_IceDeer

#include "Basic.hpp"

#include "BP_UniqueSkillModule_Tackle_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_UniqueSkillModule_Tackle_IceDeer.BP_UniqueSkillModule_Tackle_IceDeer_C
// 0x0000 (0x0118 - 0x0118)
class UBP_UniqueSkillModule_Tackle_IceDeer_C final : public UBP_UniqueSkillModule_Tackle_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_UniqueSkillModule_Tackle_IceDeer_C">();
	}
	static class UBP_UniqueSkillModule_Tackle_IceDeer_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_UniqueSkillModule_Tackle_IceDeer_C>();
	}
};
static_assert(alignof(UBP_UniqueSkillModule_Tackle_IceDeer_C) == 0x000008, "Wrong alignment on UBP_UniqueSkillModule_Tackle_IceDeer_C");
static_assert(sizeof(UBP_UniqueSkillModule_Tackle_IceDeer_C) == 0x000118, "Wrong size on UBP_UniqueSkillModule_Tackle_IceDeer_C");

}

