#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPI_CoopWeapon

#include "Basic.hpp"


namespace SDK::Params
{

// Function BPI_CoopWeapon.BPI_CoopWeapon_C.SetWeaponDamage
// 0x0004 (0x0004 - 0x0000)
struct BPI_CoopWeapon_C_SetWeaponDamage final
{
public:
	int32                                         Damageam;                                          // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BPI_CoopWeapon_C_SetWeaponDamage) == 0x000004, "Wrong alignment on BPI_CoopWeapon_C_SetWeaponDamage");
static_assert(sizeof(BPI_CoopWeapon_C_SetWeaponDamage) == 0x000004, "Wrong size on BPI_CoopWeapon_C_SetWeaponDamage");
static_assert(offsetof(BPI_CoopWeapon_C_SetWeaponDamage, Damageam) == 0x000000, "Member 'BPI_CoopWeapon_C_SetWeaponDamage::Damageam' has a wrong offset!");

// Function BPI_CoopWeapon.BPI_CoopWeapon_C.SetAttacker
// 0x0008 (0x0008 - 0x0000)
struct BPI_CoopWeapon_C_SetAttacker final
{
public:
	class AActor*                                 AttackerPal;                                       // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BPI_CoopWeapon_C_SetAttacker) == 0x000008, "Wrong alignment on BPI_CoopWeapon_C_SetAttacker");
static_assert(sizeof(BPI_CoopWeapon_C_SetAttacker) == 0x000008, "Wrong size on BPI_CoopWeapon_C_SetAttacker");
static_assert(offsetof(BPI_CoopWeapon_C_SetAttacker, AttackerPal) == 0x000000, "Member 'BPI_CoopWeapon_C_SetAttacker::AttackerPal' has a wrong offset!");

}

