#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_AssignBoard_PalSlot_Assigned

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UMG_structs.hpp"
#include "UMG_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_AssignBoard_PalSlot_Assigned.WBP_AssignBoard_PalSlot_Assigned_C
// 0x0010 (0x0288 - 0x0278)
class UWBP_AssignBoard_PalSlot_Assigned_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0278(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWBP_AssignBoard_PalSlot_C*             WBP_AssignBoard_PalSlot;                           // 0x0280(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void Construct();
	void ExecuteUbergraph_WBP_AssignBoard_PalSlot_Assigned(int32 EntryPoint);
	void SetEmpty();
	void SetIndividualParameter(class UPalIndividualCharacterParameter* Parameter);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_AssignBoard_PalSlot_Assigned_C">();
	}
	static class UWBP_AssignBoard_PalSlot_Assigned_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_AssignBoard_PalSlot_Assigned_C>();
	}
};
static_assert(alignof(UWBP_AssignBoard_PalSlot_Assigned_C) == 0x000008, "Wrong alignment on UWBP_AssignBoard_PalSlot_Assigned_C");
static_assert(sizeof(UWBP_AssignBoard_PalSlot_Assigned_C) == 0x000288, "Wrong size on UWBP_AssignBoard_PalSlot_Assigned_C");
static_assert(offsetof(UWBP_AssignBoard_PalSlot_Assigned_C, UberGraphFrame) == 0x000278, "Member 'UWBP_AssignBoard_PalSlot_Assigned_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UWBP_AssignBoard_PalSlot_Assigned_C, WBP_AssignBoard_PalSlot) == 0x000280, "Member 'UWBP_AssignBoard_PalSlot_Assigned_C::WBP_AssignBoard_PalSlot' has a wrong offset!");

}

