#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Arena_PalDetail

#include "Basic.hpp"


namespace SDK::Params
{

// Function WBP_Arena_PalDetail.WBP_Arena_PalDetail_C.ExecuteUbergraph_WBP_Arena_PalDetail
// 0x0004 (0x0004 - 0x0000)
struct WBP_Arena_PalDetail_C_ExecuteUbergraph_WBP_Arena_PalDetail final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_Arena_PalDetail_C_ExecuteUbergraph_WBP_Arena_PalDetail) == 0x000004, "Wrong alignment on WBP_Arena_PalDetail_C_ExecuteUbergraph_WBP_Arena_PalDetail");
static_assert(sizeof(WBP_Arena_PalDetail_C_ExecuteUbergraph_WBP_Arena_PalDetail) == 0x000004, "Wrong size on WBP_Arena_PalDetail_C_ExecuteUbergraph_WBP_Arena_PalDetail");
static_assert(offsetof(WBP_Arena_PalDetail_C_ExecuteUbergraph_WBP_Arena_PalDetail, EntryPoint) == 0x000000, "Member 'WBP_Arena_PalDetail_C_ExecuteUbergraph_WBP_Arena_PalDetail::EntryPoint' has a wrong offset!");

}

