#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_MainMenu_bg

#include "Basic.hpp"

#include "UMG_structs.hpp"


namespace SDK::Params
{

// Function WBP_MainMenu_bg.WBP_MainMenu_bg_C.ExecuteUbergraph_WBP_MainMenu_bg
// 0x0018 (0x0018 - 0x0000)
struct WBP_MainMenu_bg_C_ExecuteUbergraph_WBP_MainMenu_bg final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable;                                // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              Temp_byte_Variable;                                // 0x0005(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              Temp_byte_Variable_1;                              // 0x0006(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_IsDesignTime;                         // 0x0007(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UUMGSequencePlayer*                     CallFunc_PlayAnimation_ReturnValue;                // 0x0008(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              K2Node_Select_Default;                             // 0x0010(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_MainMenu_bg_C_ExecuteUbergraph_WBP_MainMenu_bg) == 0x000008, "Wrong alignment on WBP_MainMenu_bg_C_ExecuteUbergraph_WBP_MainMenu_bg");
static_assert(sizeof(WBP_MainMenu_bg_C_ExecuteUbergraph_WBP_MainMenu_bg) == 0x000018, "Wrong size on WBP_MainMenu_bg_C_ExecuteUbergraph_WBP_MainMenu_bg");
static_assert(offsetof(WBP_MainMenu_bg_C_ExecuteUbergraph_WBP_MainMenu_bg, EntryPoint) == 0x000000, "Member 'WBP_MainMenu_bg_C_ExecuteUbergraph_WBP_MainMenu_bg::EntryPoint' has a wrong offset!");
static_assert(offsetof(WBP_MainMenu_bg_C_ExecuteUbergraph_WBP_MainMenu_bg, Temp_bool_Variable) == 0x000004, "Member 'WBP_MainMenu_bg_C_ExecuteUbergraph_WBP_MainMenu_bg::Temp_bool_Variable' has a wrong offset!");
static_assert(offsetof(WBP_MainMenu_bg_C_ExecuteUbergraph_WBP_MainMenu_bg, Temp_byte_Variable) == 0x000005, "Member 'WBP_MainMenu_bg_C_ExecuteUbergraph_WBP_MainMenu_bg::Temp_byte_Variable' has a wrong offset!");
static_assert(offsetof(WBP_MainMenu_bg_C_ExecuteUbergraph_WBP_MainMenu_bg, Temp_byte_Variable_1) == 0x000006, "Member 'WBP_MainMenu_bg_C_ExecuteUbergraph_WBP_MainMenu_bg::Temp_byte_Variable_1' has a wrong offset!");
static_assert(offsetof(WBP_MainMenu_bg_C_ExecuteUbergraph_WBP_MainMenu_bg, K2Node_Event_IsDesignTime) == 0x000007, "Member 'WBP_MainMenu_bg_C_ExecuteUbergraph_WBP_MainMenu_bg::K2Node_Event_IsDesignTime' has a wrong offset!");
static_assert(offsetof(WBP_MainMenu_bg_C_ExecuteUbergraph_WBP_MainMenu_bg, CallFunc_PlayAnimation_ReturnValue) == 0x000008, "Member 'WBP_MainMenu_bg_C_ExecuteUbergraph_WBP_MainMenu_bg::CallFunc_PlayAnimation_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_MainMenu_bg_C_ExecuteUbergraph_WBP_MainMenu_bg, K2Node_Select_Default) == 0x000010, "Member 'WBP_MainMenu_bg_C_ExecuteUbergraph_WBP_MainMenu_bg::K2Node_Select_Default' has a wrong offset!");

// Function WBP_MainMenu_bg.WBP_MainMenu_bg_C.PreConstruct
// 0x0001 (0x0001 - 0x0000)
struct WBP_MainMenu_bg_C_PreConstruct final
{
public:
	bool                                          IsDesignTime;                                      // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_MainMenu_bg_C_PreConstruct) == 0x000001, "Wrong alignment on WBP_MainMenu_bg_C_PreConstruct");
static_assert(sizeof(WBP_MainMenu_bg_C_PreConstruct) == 0x000001, "Wrong size on WBP_MainMenu_bg_C_PreConstruct");
static_assert(offsetof(WBP_MainMenu_bg_C_PreConstruct, IsDesignTime) == 0x000000, "Member 'WBP_MainMenu_bg_C_PreConstruct::IsDesignTime' has a wrong offset!");

// Function WBP_MainMenu_bg.WBP_MainMenu_bg_C.SetText
// 0x0018 (0x0018 - 0x0000)
struct WBP_MainMenu_bg_C_SetText final
{
public:
	class FText                                   Text;                                              // 0x0000(0x0018)(BlueprintVisible, BlueprintReadOnly, Parm)
};
static_assert(alignof(WBP_MainMenu_bg_C_SetText) == 0x000008, "Wrong alignment on WBP_MainMenu_bg_C_SetText");
static_assert(sizeof(WBP_MainMenu_bg_C_SetText) == 0x000018, "Wrong size on WBP_MainMenu_bg_C_SetText");
static_assert(offsetof(WBP_MainMenu_bg_C_SetText, Text) == 0x000000, "Member 'WBP_MainMenu_bg_C_SetText::Text' has a wrong offset!");

}

