#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_RequirePalInfo

#include "Basic.hpp"

#include "Pal_structs.hpp"
#include "Engine_structs.hpp"
#include "UMG_structs.hpp"
#include "UMG_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_RequirePalInfo.WBP_RequirePalInfo_C
// 0x00D0 (0x0348 - 0x0278)
class UWBP_RequirePalInfo_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0278(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWidgetAnimation*                       Anm_Electric_EnableToDisable;                      // 0x0280(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UImage*                                 Base;                                              // 0x0288(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCanvasPanel*                           Canvas_RequirePal;                                 // 0x0290(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCanvasPanel*                           ElectricPower;                                     // 0x0298(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_128;                                         // 0x02A0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Line;                                              // 0x02A8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBP_PalTextBlock_C*                     Text_Electric;                                     // 0x02B0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBP_PalTextBlock_C*                     Text_RequireGenus;                                 // 0x02B8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBP_PalTextBlock_C*                     Text_RequireType;                                  // 0x02C0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBP_PalTextBlock_C*                     Text_RequireWorkSuitability;                       // 0x02C8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBP_PalTextBlock_C*                     Text_Transport;                                    // 0x02D0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_IconPalWork_C*                     WBP_IconPalWork;                                   // 0x02D8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	struct FDataTableRowHandle                    RequireGenusMSGID;                                 // 0x02E0(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor)
	struct FDataTableRowHandle                    RequireTypeMSGID;                                  // 0x02F0(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor)
	struct FDataTableRowHandle                    PowerOnlineMSGID;                                  // 0x0300(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor)
	struct FDataTableRowHandle                    PowerOfflineMSGID;                                 // 0x0310(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor)
	bool                                          PowerSufficient;                                   // 0x0320(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1E5B[0x7];                                     // 0x0321(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FDataTableRowHandle                    RequireBulletMSGID;                                // 0x0328(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor)
	class UPalMapObjectDefenseBulletLauncherModel* Launcher_Model;                                    // 0x0338(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	bool                                          BulletRequire;                                     // 0x0340(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          EnergyRequire;                                     // 0x0341(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void Construct();
	void ExecuteUbergraph_WBP_RequirePalInfo(int32 EntryPoint);
	void OnInitialized();
	void SetupBulletRequire(class UPalMapObjectDefenseBulletLauncherModel* LauncherModel);
	void SetupPowerSuffcient(class UPalMapObjectEnergyModule* Module);
	void SetWarning_Genus_Type(const class FText& GenusNames, const class FText& TypeNames);
	void SetWorkSuitability(EPalWorkSuitability WorkSuitability);
	void Update_Display(class UPalWorkBase* Work, EPalWorkSuitability WorkSuitability);
	void Update_Power_Suffcient(class UPalMapObjectEnergyModule* Module);
	void UpdateBulletRequire(int32 BulletNum);
	void UpdatePowerOrBulletRequireDisplay();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_RequirePalInfo_C">();
	}
	static class UWBP_RequirePalInfo_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_RequirePalInfo_C>();
	}
};
static_assert(alignof(UWBP_RequirePalInfo_C) == 0x000008, "Wrong alignment on UWBP_RequirePalInfo_C");
static_assert(sizeof(UWBP_RequirePalInfo_C) == 0x000348, "Wrong size on UWBP_RequirePalInfo_C");
static_assert(offsetof(UWBP_RequirePalInfo_C, UberGraphFrame) == 0x000278, "Member 'UWBP_RequirePalInfo_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UWBP_RequirePalInfo_C, Anm_Electric_EnableToDisable) == 0x000280, "Member 'UWBP_RequirePalInfo_C::Anm_Electric_EnableToDisable' has a wrong offset!");
static_assert(offsetof(UWBP_RequirePalInfo_C, Base) == 0x000288, "Member 'UWBP_RequirePalInfo_C::Base' has a wrong offset!");
static_assert(offsetof(UWBP_RequirePalInfo_C, Canvas_RequirePal) == 0x000290, "Member 'UWBP_RequirePalInfo_C::Canvas_RequirePal' has a wrong offset!");
static_assert(offsetof(UWBP_RequirePalInfo_C, ElectricPower) == 0x000298, "Member 'UWBP_RequirePalInfo_C::ElectricPower' has a wrong offset!");
static_assert(offsetof(UWBP_RequirePalInfo_C, Image_128) == 0x0002A0, "Member 'UWBP_RequirePalInfo_C::Image_128' has a wrong offset!");
static_assert(offsetof(UWBP_RequirePalInfo_C, Line) == 0x0002A8, "Member 'UWBP_RequirePalInfo_C::Line' has a wrong offset!");
static_assert(offsetof(UWBP_RequirePalInfo_C, Text_Electric) == 0x0002B0, "Member 'UWBP_RequirePalInfo_C::Text_Electric' has a wrong offset!");
static_assert(offsetof(UWBP_RequirePalInfo_C, Text_RequireGenus) == 0x0002B8, "Member 'UWBP_RequirePalInfo_C::Text_RequireGenus' has a wrong offset!");
static_assert(offsetof(UWBP_RequirePalInfo_C, Text_RequireType) == 0x0002C0, "Member 'UWBP_RequirePalInfo_C::Text_RequireType' has a wrong offset!");
static_assert(offsetof(UWBP_RequirePalInfo_C, Text_RequireWorkSuitability) == 0x0002C8, "Member 'UWBP_RequirePalInfo_C::Text_RequireWorkSuitability' has a wrong offset!");
static_assert(offsetof(UWBP_RequirePalInfo_C, Text_Transport) == 0x0002D0, "Member 'UWBP_RequirePalInfo_C::Text_Transport' has a wrong offset!");
static_assert(offsetof(UWBP_RequirePalInfo_C, WBP_IconPalWork) == 0x0002D8, "Member 'UWBP_RequirePalInfo_C::WBP_IconPalWork' has a wrong offset!");
static_assert(offsetof(UWBP_RequirePalInfo_C, RequireGenusMSGID) == 0x0002E0, "Member 'UWBP_RequirePalInfo_C::RequireGenusMSGID' has a wrong offset!");
static_assert(offsetof(UWBP_RequirePalInfo_C, RequireTypeMSGID) == 0x0002F0, "Member 'UWBP_RequirePalInfo_C::RequireTypeMSGID' has a wrong offset!");
static_assert(offsetof(UWBP_RequirePalInfo_C, PowerOnlineMSGID) == 0x000300, "Member 'UWBP_RequirePalInfo_C::PowerOnlineMSGID' has a wrong offset!");
static_assert(offsetof(UWBP_RequirePalInfo_C, PowerOfflineMSGID) == 0x000310, "Member 'UWBP_RequirePalInfo_C::PowerOfflineMSGID' has a wrong offset!");
static_assert(offsetof(UWBP_RequirePalInfo_C, PowerSufficient) == 0x000320, "Member 'UWBP_RequirePalInfo_C::PowerSufficient' has a wrong offset!");
static_assert(offsetof(UWBP_RequirePalInfo_C, RequireBulletMSGID) == 0x000328, "Member 'UWBP_RequirePalInfo_C::RequireBulletMSGID' has a wrong offset!");
static_assert(offsetof(UWBP_RequirePalInfo_C, Launcher_Model) == 0x000338, "Member 'UWBP_RequirePalInfo_C::Launcher_Model' has a wrong offset!");
static_assert(offsetof(UWBP_RequirePalInfo_C, BulletRequire) == 0x000340, "Member 'UWBP_RequirePalInfo_C::BulletRequire' has a wrong offset!");
static_assert(offsetof(UWBP_RequirePalInfo_C, EnergyRequire) == 0x000341, "Member 'UWBP_RequirePalInfo_C::EnergyRequire' has a wrong offset!");

}

