#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_CommonWorkRequirement

#include "Basic.hpp"

#include "Pal_structs.hpp"


namespace SDK::Params
{

// Function WBP_CommonWorkRequirement.WBP_CommonWorkRequirement_C.ExecuteUbergraph_WBP_CommonWorkRequirement
// 0x0070 (0x0070 - 0x0000)
struct WBP_CommonWorkRequirement_C_ExecuteUbergraph_WBP_CommonWorkRequirement final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4ECA[0x4];                                     // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UPalHUDDispatchParameterBase*           CallFunc_GetParam_ReturnValue;                     // 0x0008(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(class UPalWorkBase* Work)>     K2Node_CreateDelegate_OutputDelegate;              // 0x0010(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UPalUIMapObjectStatusIndicatorParameterBase* K2Node_DynamicCast_AsPal_UIMap_Object_Status_Indicator_Parameter_Base; // 0x0020(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0028(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4ECB[0x7];                                     // 0x0029(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UPalMapObjectConcreteModelBase*         CallFunc_GetConcreteModel_ReturnValue;             // 0x0030(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UPalMapObjectEnergyModule*              CallFunc_GetEnergyModule_ReturnValue;              // 0x0038(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UPalMapObjectDefenseBulletLauncherModel* K2Node_DynamicCast_AsPal_Map_Object_Defense_Bullet_Launcher_Model; // 0x0040(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_1;                     // 0x0048(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4ECC[0x7];                                     // 0x0049(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UPalMapObjectWorkeeModule*              CallFunc_GetWorkeeModule_ReturnValue;              // 0x0050(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UPalWorkProgress*                       CallFunc_GetWorkProgress_ReturnValue;              // 0x0058(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UPalWorkBase*                           CallFunc_GetWork_ReturnValue;                      // 0x0060(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0068(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_1;                    // 0x0069(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_CommonWorkRequirement_C_ExecuteUbergraph_WBP_CommonWorkRequirement) == 0x000008, "Wrong alignment on WBP_CommonWorkRequirement_C_ExecuteUbergraph_WBP_CommonWorkRequirement");
static_assert(sizeof(WBP_CommonWorkRequirement_C_ExecuteUbergraph_WBP_CommonWorkRequirement) == 0x000070, "Wrong size on WBP_CommonWorkRequirement_C_ExecuteUbergraph_WBP_CommonWorkRequirement");
static_assert(offsetof(WBP_CommonWorkRequirement_C_ExecuteUbergraph_WBP_CommonWorkRequirement, EntryPoint) == 0x000000, "Member 'WBP_CommonWorkRequirement_C_ExecuteUbergraph_WBP_CommonWorkRequirement::EntryPoint' has a wrong offset!");
static_assert(offsetof(WBP_CommonWorkRequirement_C_ExecuteUbergraph_WBP_CommonWorkRequirement, CallFunc_GetParam_ReturnValue) == 0x000008, "Member 'WBP_CommonWorkRequirement_C_ExecuteUbergraph_WBP_CommonWorkRequirement::CallFunc_GetParam_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_CommonWorkRequirement_C_ExecuteUbergraph_WBP_CommonWorkRequirement, K2Node_CreateDelegate_OutputDelegate) == 0x000010, "Member 'WBP_CommonWorkRequirement_C_ExecuteUbergraph_WBP_CommonWorkRequirement::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(WBP_CommonWorkRequirement_C_ExecuteUbergraph_WBP_CommonWorkRequirement, K2Node_DynamicCast_AsPal_UIMap_Object_Status_Indicator_Parameter_Base) == 0x000020, "Member 'WBP_CommonWorkRequirement_C_ExecuteUbergraph_WBP_CommonWorkRequirement::K2Node_DynamicCast_AsPal_UIMap_Object_Status_Indicator_Parameter_Base' has a wrong offset!");
static_assert(offsetof(WBP_CommonWorkRequirement_C_ExecuteUbergraph_WBP_CommonWorkRequirement, K2Node_DynamicCast_bSuccess) == 0x000028, "Member 'WBP_CommonWorkRequirement_C_ExecuteUbergraph_WBP_CommonWorkRequirement::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(WBP_CommonWorkRequirement_C_ExecuteUbergraph_WBP_CommonWorkRequirement, CallFunc_GetConcreteModel_ReturnValue) == 0x000030, "Member 'WBP_CommonWorkRequirement_C_ExecuteUbergraph_WBP_CommonWorkRequirement::CallFunc_GetConcreteModel_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_CommonWorkRequirement_C_ExecuteUbergraph_WBP_CommonWorkRequirement, CallFunc_GetEnergyModule_ReturnValue) == 0x000038, "Member 'WBP_CommonWorkRequirement_C_ExecuteUbergraph_WBP_CommonWorkRequirement::CallFunc_GetEnergyModule_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_CommonWorkRequirement_C_ExecuteUbergraph_WBP_CommonWorkRequirement, K2Node_DynamicCast_AsPal_Map_Object_Defense_Bullet_Launcher_Model) == 0x000040, "Member 'WBP_CommonWorkRequirement_C_ExecuteUbergraph_WBP_CommonWorkRequirement::K2Node_DynamicCast_AsPal_Map_Object_Defense_Bullet_Launcher_Model' has a wrong offset!");
static_assert(offsetof(WBP_CommonWorkRequirement_C_ExecuteUbergraph_WBP_CommonWorkRequirement, K2Node_DynamicCast_bSuccess_1) == 0x000048, "Member 'WBP_CommonWorkRequirement_C_ExecuteUbergraph_WBP_CommonWorkRequirement::K2Node_DynamicCast_bSuccess_1' has a wrong offset!");
static_assert(offsetof(WBP_CommonWorkRequirement_C_ExecuteUbergraph_WBP_CommonWorkRequirement, CallFunc_GetWorkeeModule_ReturnValue) == 0x000050, "Member 'WBP_CommonWorkRequirement_C_ExecuteUbergraph_WBP_CommonWorkRequirement::CallFunc_GetWorkeeModule_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_CommonWorkRequirement_C_ExecuteUbergraph_WBP_CommonWorkRequirement, CallFunc_GetWorkProgress_ReturnValue) == 0x000058, "Member 'WBP_CommonWorkRequirement_C_ExecuteUbergraph_WBP_CommonWorkRequirement::CallFunc_GetWorkProgress_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_CommonWorkRequirement_C_ExecuteUbergraph_WBP_CommonWorkRequirement, CallFunc_GetWork_ReturnValue) == 0x000060, "Member 'WBP_CommonWorkRequirement_C_ExecuteUbergraph_WBP_CommonWorkRequirement::CallFunc_GetWork_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_CommonWorkRequirement_C_ExecuteUbergraph_WBP_CommonWorkRequirement, CallFunc_IsValid_ReturnValue) == 0x000068, "Member 'WBP_CommonWorkRequirement_C_ExecuteUbergraph_WBP_CommonWorkRequirement::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_CommonWorkRequirement_C_ExecuteUbergraph_WBP_CommonWorkRequirement, CallFunc_IsValid_ReturnValue_1) == 0x000069, "Member 'WBP_CommonWorkRequirement_C_ExecuteUbergraph_WBP_CommonWorkRequirement::CallFunc_IsValid_ReturnValue_1' has a wrong offset!");

// Function WBP_CommonWorkRequirement.WBP_CommonWorkRequirement_C.On Updated Worker Pal
// 0x0010 (0x0010 - 0x0000)
struct WBP_CommonWorkRequirement_C_On_Updated_Worker_Pal final
{
public:
	class UPalWorkBase*                           Work;                                              // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          HasAssign;                                         // 0x0008(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EPalWorkSuitability                           CallFunc_GetWorkSuitability_ReturnValue;           // 0x0009(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_CommonWorkRequirement_C_On_Updated_Worker_Pal) == 0x000008, "Wrong alignment on WBP_CommonWorkRequirement_C_On_Updated_Worker_Pal");
static_assert(sizeof(WBP_CommonWorkRequirement_C_On_Updated_Worker_Pal) == 0x000010, "Wrong size on WBP_CommonWorkRequirement_C_On_Updated_Worker_Pal");
static_assert(offsetof(WBP_CommonWorkRequirement_C_On_Updated_Worker_Pal, Work) == 0x000000, "Member 'WBP_CommonWorkRequirement_C_On_Updated_Worker_Pal::Work' has a wrong offset!");
static_assert(offsetof(WBP_CommonWorkRequirement_C_On_Updated_Worker_Pal, HasAssign) == 0x000008, "Member 'WBP_CommonWorkRequirement_C_On_Updated_Worker_Pal::HasAssign' has a wrong offset!");
static_assert(offsetof(WBP_CommonWorkRequirement_C_On_Updated_Worker_Pal, CallFunc_GetWorkSuitability_ReturnValue) == 0x000009, "Member 'WBP_CommonWorkRequirement_C_On_Updated_Worker_Pal::CallFunc_GetWorkSuitability_ReturnValue' has a wrong offset!");

}

