#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_MapMarker_Win

#include "Basic.hpp"

#include "SlateCore_structs.hpp"
#include "Engine_structs.hpp"


namespace SDK::Params
{

// Function WBP_MapMarker_Win.WBP_MapMarker_Win_C.ChangeCustomIcon__DelegateSignature
// 0x0010 (0x0010 - 0x0000)
struct WBP_MapMarker_Win_C_ChangeCustomIcon__DelegateSignature final
{
public:
	class UWBP_Map_IconCustom_C*                  Icon;                                              // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	int32                                         Param_Index;                                       // 0x0008(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_MapMarker_Win_C_ChangeCustomIcon__DelegateSignature) == 0x000008, "Wrong alignment on WBP_MapMarker_Win_C_ChangeCustomIcon__DelegateSignature");
static_assert(sizeof(WBP_MapMarker_Win_C_ChangeCustomIcon__DelegateSignature) == 0x000010, "Wrong size on WBP_MapMarker_Win_C_ChangeCustomIcon__DelegateSignature");
static_assert(offsetof(WBP_MapMarker_Win_C_ChangeCustomIcon__DelegateSignature, Icon) == 0x000000, "Member 'WBP_MapMarker_Win_C_ChangeCustomIcon__DelegateSignature::Icon' has a wrong offset!");
static_assert(offsetof(WBP_MapMarker_Win_C_ChangeCustomIcon__DelegateSignature, Param_Index) == 0x000008, "Member 'WBP_MapMarker_Win_C_ChangeCustomIcon__DelegateSignature::Param_Index' has a wrong offset!");

// Function WBP_MapMarker_Win.WBP_MapMarker_Win_C.ChangeIconType
// 0x0004 (0x0004 - 0x0000)
struct WBP_MapMarker_Win_C_ChangeIconType final
{
public:
	int32                                         Param_Index;                                       // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_MapMarker_Win_C_ChangeIconType) == 0x000004, "Wrong alignment on WBP_MapMarker_Win_C_ChangeIconType");
static_assert(sizeof(WBP_MapMarker_Win_C_ChangeIconType) == 0x000004, "Wrong size on WBP_MapMarker_Win_C_ChangeIconType");
static_assert(offsetof(WBP_MapMarker_Win_C_ChangeIconType, Param_Index) == 0x000000, "Member 'WBP_MapMarker_Win_C_ChangeIconType::Param_Index' has a wrong offset!");

// Function WBP_MapMarker_Win.WBP_MapMarker_Win_C.DoCustomNavigation
// 0x0040 (0x0040 - 0x0000)
struct WBP_MapMarker_Win_C_DoCustomNavigation final
{
public:
	EUINavigation                                 Param_Navigation;                                  // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4E67[0x7];                                     // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UWidget*                                ReturnValue;                                       // 0x0008(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, NoDestructor, HasGetValueTypeHash)
	TArray<class UWidget*>                        CallFunc_GetAllChildren_ReturnValue;               // 0x0010(0x0010)(ReferenceParm, ContainsInstancedReference)
	int32                                         CallFunc_Array_LastIndex_ReturnValue;              // 0x0020(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4E68[0x4];                                     // 0x0024(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UWidget*                                CallFunc_Array_Get_Item;                           // 0x0028(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UWBP_MapMarker_Content_C*               K2Node_DynamicCast_AsWBP_Map_Marker_Content;       // 0x0030(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0038(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_MapMarker_Win_C_DoCustomNavigation) == 0x000008, "Wrong alignment on WBP_MapMarker_Win_C_DoCustomNavigation");
static_assert(sizeof(WBP_MapMarker_Win_C_DoCustomNavigation) == 0x000040, "Wrong size on WBP_MapMarker_Win_C_DoCustomNavigation");
static_assert(offsetof(WBP_MapMarker_Win_C_DoCustomNavigation, Param_Navigation) == 0x000000, "Member 'WBP_MapMarker_Win_C_DoCustomNavigation::Param_Navigation' has a wrong offset!");
static_assert(offsetof(WBP_MapMarker_Win_C_DoCustomNavigation, ReturnValue) == 0x000008, "Member 'WBP_MapMarker_Win_C_DoCustomNavigation::ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_MapMarker_Win_C_DoCustomNavigation, CallFunc_GetAllChildren_ReturnValue) == 0x000010, "Member 'WBP_MapMarker_Win_C_DoCustomNavigation::CallFunc_GetAllChildren_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_MapMarker_Win_C_DoCustomNavigation, CallFunc_Array_LastIndex_ReturnValue) == 0x000020, "Member 'WBP_MapMarker_Win_C_DoCustomNavigation::CallFunc_Array_LastIndex_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_MapMarker_Win_C_DoCustomNavigation, CallFunc_Array_Get_Item) == 0x000028, "Member 'WBP_MapMarker_Win_C_DoCustomNavigation::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(WBP_MapMarker_Win_C_DoCustomNavigation, K2Node_DynamicCast_AsWBP_Map_Marker_Content) == 0x000030, "Member 'WBP_MapMarker_Win_C_DoCustomNavigation::K2Node_DynamicCast_AsWBP_Map_Marker_Content' has a wrong offset!");
static_assert(offsetof(WBP_MapMarker_Win_C_DoCustomNavigation, K2Node_DynamicCast_bSuccess) == 0x000038, "Member 'WBP_MapMarker_Win_C_DoCustomNavigation::K2Node_DynamicCast_bSuccess' has a wrong offset!");

// Function WBP_MapMarker_Win.WBP_MapMarker_Win_C.ExecuteUbergraph_WBP_MapMarker_Win
// 0x02F8 (0x02F8 - 0x0000)
struct WBP_MapMarker_Win_C_ExecuteUbergraph_WBP_MapMarker_Win final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable;                                // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4E69[0x3];                                     // 0x0005(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UMaterialInterface*                     Temp_object_Variable;                              // 0x0008(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UMaterialInterface*                     Temp_object_Variable_1;                            // 0x0010(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable_1;                              // 0x0018(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4E6A[0x7];                                     // 0x0019(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UMaterialInterface*                     Temp_object_Variable_2;                            // 0x0020(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UMaterialInterface*                     Temp_object_Variable_3;                            // 0x0028(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0030(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x0034(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0038(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable_1;                   // 0x003C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate;              // 0x0040(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable_1;                  // 0x0050(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(int32 Index)>                  K2Node_CreateDelegate_OutputDelegate_1;            // 0x0054(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue_1;                 // 0x0064(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         K2Node_CustomEvent_Index;                          // 0x0068(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4E6B[0x4];                                     // 0x006C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UWBP_Map_IconCustom_C*                  K2Node_CustomEvent_CustomIcon;                     // 0x0070(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UTexture2D*                             CallFunc_Array_Get_Item;                           // 0x0078(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UWBP_MapMarker_Content_C*               CallFunc_Array_Get_Item_1;                         // 0x0080(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_NotEqual_IntInt_ReturnValue;              // 0x0088(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4E6C[0x7];                                     // 0x0089(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UWBP_MapMarker_Content_C*               CallFunc_Array_Get_Item_2;                         // 0x0090(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UWBP_MapMarker_Content_C*               CallFunc_Array_Get_Item_3;                         // 0x0098(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	struct FFocusEvent                            K2Node_Event_InFocusEvent;                         // 0x00A0(0x0008)(NoDestructor)
	class UWBP_MapMarker_Content_C*               CallFunc_Array_Get_Item_4;                         // 0x00A8(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UWBP_MapMarker_Content_C*               CallFunc_Array_Get_Item_5;                         // 0x00B0(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x00B8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x00BC(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4E6D[0x3];                                     // 0x00BD(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UPalGameSetting*                        CallFunc_GetGameSetting_ReturnValue;               // 0x00C0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UPalLocationManager*                    CallFunc_GetLocationManager_ReturnValue;           // 0x00C8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	int64                                         CallFunc_Conv_IntToInt64_ReturnValue;              // 0x00D0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_GetLocalCustomLocationCount_ReturnValue;  // 0x00D8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4E6E[0x4];                                     // 0x00DC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FFormatArgumentData                    K2Node_MakeStruct_FormatArgumentData;              // 0x00E0(0x0050)(HasGetValueTypeHash)
	int64                                         CallFunc_Conv_IntToInt64_ReturnValue_1;            // 0x0130(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_GreaterEqual_IntInt_ReturnValue;          // 0x0138(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4E6F[0x7];                                     // 0x0139(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FFormatArgumentData                    K2Node_MakeStruct_FormatArgumentData_1;            // 0x0140(0x0050)(HasGetValueTypeHash)
	TArray<struct FFormatArgumentData>            K2Node_MakeArray_Array;                            // 0x0190(0x0010)(ReferenceParm)
	class UMaterialInterface*                     K2Node_Select_Default;                             // 0x01A0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class FText                                   CallFunc_Format_ReturnValue;                       // 0x01A8(0x0018)()
	class UPalGameSetting*                        CallFunc_GetGameSetting_ReturnValue_1;             // 0x01C0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UPalLocationManager*                    CallFunc_GetLocationManager_ReturnValue_1;         // 0x01C8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	int64                                         CallFunc_Conv_IntToInt64_ReturnValue_2;            // 0x01D0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_GetLocalCustomLocationCount_ReturnValue_1; // 0x01D8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4E70[0x4];                                     // 0x01DC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FFormatArgumentData                    K2Node_MakeStruct_FormatArgumentData_2;            // 0x01E0(0x0050)(HasGetValueTypeHash)
	int64                                         CallFunc_Conv_IntToInt64_ReturnValue_3;            // 0x0230(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_GreaterEqual_IntInt_ReturnValue_1;        // 0x0238(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4E71[0x7];                                     // 0x0239(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FFormatArgumentData                    K2Node_MakeStruct_FormatArgumentData_3;            // 0x0240(0x0050)(HasGetValueTypeHash)
	TArray<struct FFormatArgumentData>            K2Node_MakeArray_Array_1;                          // 0x0290(0x0010)(ReferenceParm)
	class UMaterialInterface*                     K2Node_Select_Default_1;                           // 0x02A0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class FText                                   CallFunc_Format_ReturnValue_1;                     // 0x02A8(0x0018)()
	class UPalLocationPoint*                      CallFunc_GetLocationPoint_LocationPoint;           // 0x02C0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UPalLocationPoint_Custom*               K2Node_DynamicCast_AsPal_Location_Point_Custom;    // 0x02C8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x02D0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4E72[0x3];                                     // 0x02D1(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_GetIconType_ReturnValue;                  // 0x02D4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UWBP_MapMarker_Content_C*               CallFunc_Array_Get_Item_6;                         // 0x02D8(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue_1;               // 0x02E0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue_1;                // 0x02E4(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4E73[0x3];                                     // 0x02E5(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class UWBP_MapMarker_Content_C*>       K2Node_MakeArray_Array_2;                          // 0x02E8(0x0010)(ReferenceParm, ContainsInstancedReference)
};
static_assert(alignof(WBP_MapMarker_Win_C_ExecuteUbergraph_WBP_MapMarker_Win) == 0x000008, "Wrong alignment on WBP_MapMarker_Win_C_ExecuteUbergraph_WBP_MapMarker_Win");
static_assert(sizeof(WBP_MapMarker_Win_C_ExecuteUbergraph_WBP_MapMarker_Win) == 0x0002F8, "Wrong size on WBP_MapMarker_Win_C_ExecuteUbergraph_WBP_MapMarker_Win");
static_assert(offsetof(WBP_MapMarker_Win_C_ExecuteUbergraph_WBP_MapMarker_Win, EntryPoint) == 0x000000, "Member 'WBP_MapMarker_Win_C_ExecuteUbergraph_WBP_MapMarker_Win::EntryPoint' has a wrong offset!");
static_assert(offsetof(WBP_MapMarker_Win_C_ExecuteUbergraph_WBP_MapMarker_Win, Temp_bool_Variable) == 0x000004, "Member 'WBP_MapMarker_Win_C_ExecuteUbergraph_WBP_MapMarker_Win::Temp_bool_Variable' has a wrong offset!");
static_assert(offsetof(WBP_MapMarker_Win_C_ExecuteUbergraph_WBP_MapMarker_Win, Temp_object_Variable) == 0x000008, "Member 'WBP_MapMarker_Win_C_ExecuteUbergraph_WBP_MapMarker_Win::Temp_object_Variable' has a wrong offset!");
static_assert(offsetof(WBP_MapMarker_Win_C_ExecuteUbergraph_WBP_MapMarker_Win, Temp_object_Variable_1) == 0x000010, "Member 'WBP_MapMarker_Win_C_ExecuteUbergraph_WBP_MapMarker_Win::Temp_object_Variable_1' has a wrong offset!");
static_assert(offsetof(WBP_MapMarker_Win_C_ExecuteUbergraph_WBP_MapMarker_Win, Temp_bool_Variable_1) == 0x000018, "Member 'WBP_MapMarker_Win_C_ExecuteUbergraph_WBP_MapMarker_Win::Temp_bool_Variable_1' has a wrong offset!");
static_assert(offsetof(WBP_MapMarker_Win_C_ExecuteUbergraph_WBP_MapMarker_Win, Temp_object_Variable_2) == 0x000020, "Member 'WBP_MapMarker_Win_C_ExecuteUbergraph_WBP_MapMarker_Win::Temp_object_Variable_2' has a wrong offset!");
static_assert(offsetof(WBP_MapMarker_Win_C_ExecuteUbergraph_WBP_MapMarker_Win, Temp_object_Variable_3) == 0x000028, "Member 'WBP_MapMarker_Win_C_ExecuteUbergraph_WBP_MapMarker_Win::Temp_object_Variable_3' has a wrong offset!");
static_assert(offsetof(WBP_MapMarker_Win_C_ExecuteUbergraph_WBP_MapMarker_Win, Temp_int_Array_Index_Variable) == 0x000030, "Member 'WBP_MapMarker_Win_C_ExecuteUbergraph_WBP_MapMarker_Win::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(WBP_MapMarker_Win_C_ExecuteUbergraph_WBP_MapMarker_Win, Temp_int_Loop_Counter_Variable) == 0x000034, "Member 'WBP_MapMarker_Win_C_ExecuteUbergraph_WBP_MapMarker_Win::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(WBP_MapMarker_Win_C_ExecuteUbergraph_WBP_MapMarker_Win, CallFunc_Add_IntInt_ReturnValue) == 0x000038, "Member 'WBP_MapMarker_Win_C_ExecuteUbergraph_WBP_MapMarker_Win::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_MapMarker_Win_C_ExecuteUbergraph_WBP_MapMarker_Win, Temp_int_Array_Index_Variable_1) == 0x00003C, "Member 'WBP_MapMarker_Win_C_ExecuteUbergraph_WBP_MapMarker_Win::Temp_int_Array_Index_Variable_1' has a wrong offset!");
static_assert(offsetof(WBP_MapMarker_Win_C_ExecuteUbergraph_WBP_MapMarker_Win, K2Node_CreateDelegate_OutputDelegate) == 0x000040, "Member 'WBP_MapMarker_Win_C_ExecuteUbergraph_WBP_MapMarker_Win::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(WBP_MapMarker_Win_C_ExecuteUbergraph_WBP_MapMarker_Win, Temp_int_Loop_Counter_Variable_1) == 0x000050, "Member 'WBP_MapMarker_Win_C_ExecuteUbergraph_WBP_MapMarker_Win::Temp_int_Loop_Counter_Variable_1' has a wrong offset!");
static_assert(offsetof(WBP_MapMarker_Win_C_ExecuteUbergraph_WBP_MapMarker_Win, K2Node_CreateDelegate_OutputDelegate_1) == 0x000054, "Member 'WBP_MapMarker_Win_C_ExecuteUbergraph_WBP_MapMarker_Win::K2Node_CreateDelegate_OutputDelegate_1' has a wrong offset!");
static_assert(offsetof(WBP_MapMarker_Win_C_ExecuteUbergraph_WBP_MapMarker_Win, CallFunc_Add_IntInt_ReturnValue_1) == 0x000064, "Member 'WBP_MapMarker_Win_C_ExecuteUbergraph_WBP_MapMarker_Win::CallFunc_Add_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_MapMarker_Win_C_ExecuteUbergraph_WBP_MapMarker_Win, K2Node_CustomEvent_Index) == 0x000068, "Member 'WBP_MapMarker_Win_C_ExecuteUbergraph_WBP_MapMarker_Win::K2Node_CustomEvent_Index' has a wrong offset!");
static_assert(offsetof(WBP_MapMarker_Win_C_ExecuteUbergraph_WBP_MapMarker_Win, K2Node_CustomEvent_CustomIcon) == 0x000070, "Member 'WBP_MapMarker_Win_C_ExecuteUbergraph_WBP_MapMarker_Win::K2Node_CustomEvent_CustomIcon' has a wrong offset!");
static_assert(offsetof(WBP_MapMarker_Win_C_ExecuteUbergraph_WBP_MapMarker_Win, CallFunc_Array_Get_Item) == 0x000078, "Member 'WBP_MapMarker_Win_C_ExecuteUbergraph_WBP_MapMarker_Win::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(WBP_MapMarker_Win_C_ExecuteUbergraph_WBP_MapMarker_Win, CallFunc_Array_Get_Item_1) == 0x000080, "Member 'WBP_MapMarker_Win_C_ExecuteUbergraph_WBP_MapMarker_Win::CallFunc_Array_Get_Item_1' has a wrong offset!");
static_assert(offsetof(WBP_MapMarker_Win_C_ExecuteUbergraph_WBP_MapMarker_Win, CallFunc_NotEqual_IntInt_ReturnValue) == 0x000088, "Member 'WBP_MapMarker_Win_C_ExecuteUbergraph_WBP_MapMarker_Win::CallFunc_NotEqual_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_MapMarker_Win_C_ExecuteUbergraph_WBP_MapMarker_Win, CallFunc_Array_Get_Item_2) == 0x000090, "Member 'WBP_MapMarker_Win_C_ExecuteUbergraph_WBP_MapMarker_Win::CallFunc_Array_Get_Item_2' has a wrong offset!");
static_assert(offsetof(WBP_MapMarker_Win_C_ExecuteUbergraph_WBP_MapMarker_Win, CallFunc_Array_Get_Item_3) == 0x000098, "Member 'WBP_MapMarker_Win_C_ExecuteUbergraph_WBP_MapMarker_Win::CallFunc_Array_Get_Item_3' has a wrong offset!");
static_assert(offsetof(WBP_MapMarker_Win_C_ExecuteUbergraph_WBP_MapMarker_Win, K2Node_Event_InFocusEvent) == 0x0000A0, "Member 'WBP_MapMarker_Win_C_ExecuteUbergraph_WBP_MapMarker_Win::K2Node_Event_InFocusEvent' has a wrong offset!");
static_assert(offsetof(WBP_MapMarker_Win_C_ExecuteUbergraph_WBP_MapMarker_Win, CallFunc_Array_Get_Item_4) == 0x0000A8, "Member 'WBP_MapMarker_Win_C_ExecuteUbergraph_WBP_MapMarker_Win::CallFunc_Array_Get_Item_4' has a wrong offset!");
static_assert(offsetof(WBP_MapMarker_Win_C_ExecuteUbergraph_WBP_MapMarker_Win, CallFunc_Array_Get_Item_5) == 0x0000B0, "Member 'WBP_MapMarker_Win_C_ExecuteUbergraph_WBP_MapMarker_Win::CallFunc_Array_Get_Item_5' has a wrong offset!");
static_assert(offsetof(WBP_MapMarker_Win_C_ExecuteUbergraph_WBP_MapMarker_Win, CallFunc_Array_Length_ReturnValue) == 0x0000B8, "Member 'WBP_MapMarker_Win_C_ExecuteUbergraph_WBP_MapMarker_Win::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_MapMarker_Win_C_ExecuteUbergraph_WBP_MapMarker_Win, CallFunc_Less_IntInt_ReturnValue) == 0x0000BC, "Member 'WBP_MapMarker_Win_C_ExecuteUbergraph_WBP_MapMarker_Win::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_MapMarker_Win_C_ExecuteUbergraph_WBP_MapMarker_Win, CallFunc_GetGameSetting_ReturnValue) == 0x0000C0, "Member 'WBP_MapMarker_Win_C_ExecuteUbergraph_WBP_MapMarker_Win::CallFunc_GetGameSetting_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_MapMarker_Win_C_ExecuteUbergraph_WBP_MapMarker_Win, CallFunc_GetLocationManager_ReturnValue) == 0x0000C8, "Member 'WBP_MapMarker_Win_C_ExecuteUbergraph_WBP_MapMarker_Win::CallFunc_GetLocationManager_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_MapMarker_Win_C_ExecuteUbergraph_WBP_MapMarker_Win, CallFunc_Conv_IntToInt64_ReturnValue) == 0x0000D0, "Member 'WBP_MapMarker_Win_C_ExecuteUbergraph_WBP_MapMarker_Win::CallFunc_Conv_IntToInt64_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_MapMarker_Win_C_ExecuteUbergraph_WBP_MapMarker_Win, CallFunc_GetLocalCustomLocationCount_ReturnValue) == 0x0000D8, "Member 'WBP_MapMarker_Win_C_ExecuteUbergraph_WBP_MapMarker_Win::CallFunc_GetLocalCustomLocationCount_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_MapMarker_Win_C_ExecuteUbergraph_WBP_MapMarker_Win, K2Node_MakeStruct_FormatArgumentData) == 0x0000E0, "Member 'WBP_MapMarker_Win_C_ExecuteUbergraph_WBP_MapMarker_Win::K2Node_MakeStruct_FormatArgumentData' has a wrong offset!");
static_assert(offsetof(WBP_MapMarker_Win_C_ExecuteUbergraph_WBP_MapMarker_Win, CallFunc_Conv_IntToInt64_ReturnValue_1) == 0x000130, "Member 'WBP_MapMarker_Win_C_ExecuteUbergraph_WBP_MapMarker_Win::CallFunc_Conv_IntToInt64_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_MapMarker_Win_C_ExecuteUbergraph_WBP_MapMarker_Win, CallFunc_GreaterEqual_IntInt_ReturnValue) == 0x000138, "Member 'WBP_MapMarker_Win_C_ExecuteUbergraph_WBP_MapMarker_Win::CallFunc_GreaterEqual_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_MapMarker_Win_C_ExecuteUbergraph_WBP_MapMarker_Win, K2Node_MakeStruct_FormatArgumentData_1) == 0x000140, "Member 'WBP_MapMarker_Win_C_ExecuteUbergraph_WBP_MapMarker_Win::K2Node_MakeStruct_FormatArgumentData_1' has a wrong offset!");
static_assert(offsetof(WBP_MapMarker_Win_C_ExecuteUbergraph_WBP_MapMarker_Win, K2Node_MakeArray_Array) == 0x000190, "Member 'WBP_MapMarker_Win_C_ExecuteUbergraph_WBP_MapMarker_Win::K2Node_MakeArray_Array' has a wrong offset!");
static_assert(offsetof(WBP_MapMarker_Win_C_ExecuteUbergraph_WBP_MapMarker_Win, K2Node_Select_Default) == 0x0001A0, "Member 'WBP_MapMarker_Win_C_ExecuteUbergraph_WBP_MapMarker_Win::K2Node_Select_Default' has a wrong offset!");
static_assert(offsetof(WBP_MapMarker_Win_C_ExecuteUbergraph_WBP_MapMarker_Win, CallFunc_Format_ReturnValue) == 0x0001A8, "Member 'WBP_MapMarker_Win_C_ExecuteUbergraph_WBP_MapMarker_Win::CallFunc_Format_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_MapMarker_Win_C_ExecuteUbergraph_WBP_MapMarker_Win, CallFunc_GetGameSetting_ReturnValue_1) == 0x0001C0, "Member 'WBP_MapMarker_Win_C_ExecuteUbergraph_WBP_MapMarker_Win::CallFunc_GetGameSetting_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_MapMarker_Win_C_ExecuteUbergraph_WBP_MapMarker_Win, CallFunc_GetLocationManager_ReturnValue_1) == 0x0001C8, "Member 'WBP_MapMarker_Win_C_ExecuteUbergraph_WBP_MapMarker_Win::CallFunc_GetLocationManager_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_MapMarker_Win_C_ExecuteUbergraph_WBP_MapMarker_Win, CallFunc_Conv_IntToInt64_ReturnValue_2) == 0x0001D0, "Member 'WBP_MapMarker_Win_C_ExecuteUbergraph_WBP_MapMarker_Win::CallFunc_Conv_IntToInt64_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(WBP_MapMarker_Win_C_ExecuteUbergraph_WBP_MapMarker_Win, CallFunc_GetLocalCustomLocationCount_ReturnValue_1) == 0x0001D8, "Member 'WBP_MapMarker_Win_C_ExecuteUbergraph_WBP_MapMarker_Win::CallFunc_GetLocalCustomLocationCount_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_MapMarker_Win_C_ExecuteUbergraph_WBP_MapMarker_Win, K2Node_MakeStruct_FormatArgumentData_2) == 0x0001E0, "Member 'WBP_MapMarker_Win_C_ExecuteUbergraph_WBP_MapMarker_Win::K2Node_MakeStruct_FormatArgumentData_2' has a wrong offset!");
static_assert(offsetof(WBP_MapMarker_Win_C_ExecuteUbergraph_WBP_MapMarker_Win, CallFunc_Conv_IntToInt64_ReturnValue_3) == 0x000230, "Member 'WBP_MapMarker_Win_C_ExecuteUbergraph_WBP_MapMarker_Win::CallFunc_Conv_IntToInt64_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(WBP_MapMarker_Win_C_ExecuteUbergraph_WBP_MapMarker_Win, CallFunc_GreaterEqual_IntInt_ReturnValue_1) == 0x000238, "Member 'WBP_MapMarker_Win_C_ExecuteUbergraph_WBP_MapMarker_Win::CallFunc_GreaterEqual_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_MapMarker_Win_C_ExecuteUbergraph_WBP_MapMarker_Win, K2Node_MakeStruct_FormatArgumentData_3) == 0x000240, "Member 'WBP_MapMarker_Win_C_ExecuteUbergraph_WBP_MapMarker_Win::K2Node_MakeStruct_FormatArgumentData_3' has a wrong offset!");
static_assert(offsetof(WBP_MapMarker_Win_C_ExecuteUbergraph_WBP_MapMarker_Win, K2Node_MakeArray_Array_1) == 0x000290, "Member 'WBP_MapMarker_Win_C_ExecuteUbergraph_WBP_MapMarker_Win::K2Node_MakeArray_Array_1' has a wrong offset!");
static_assert(offsetof(WBP_MapMarker_Win_C_ExecuteUbergraph_WBP_MapMarker_Win, K2Node_Select_Default_1) == 0x0002A0, "Member 'WBP_MapMarker_Win_C_ExecuteUbergraph_WBP_MapMarker_Win::K2Node_Select_Default_1' has a wrong offset!");
static_assert(offsetof(WBP_MapMarker_Win_C_ExecuteUbergraph_WBP_MapMarker_Win, CallFunc_Format_ReturnValue_1) == 0x0002A8, "Member 'WBP_MapMarker_Win_C_ExecuteUbergraph_WBP_MapMarker_Win::CallFunc_Format_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_MapMarker_Win_C_ExecuteUbergraph_WBP_MapMarker_Win, CallFunc_GetLocationPoint_LocationPoint) == 0x0002C0, "Member 'WBP_MapMarker_Win_C_ExecuteUbergraph_WBP_MapMarker_Win::CallFunc_GetLocationPoint_LocationPoint' has a wrong offset!");
static_assert(offsetof(WBP_MapMarker_Win_C_ExecuteUbergraph_WBP_MapMarker_Win, K2Node_DynamicCast_AsPal_Location_Point_Custom) == 0x0002C8, "Member 'WBP_MapMarker_Win_C_ExecuteUbergraph_WBP_MapMarker_Win::K2Node_DynamicCast_AsPal_Location_Point_Custom' has a wrong offset!");
static_assert(offsetof(WBP_MapMarker_Win_C_ExecuteUbergraph_WBP_MapMarker_Win, K2Node_DynamicCast_bSuccess) == 0x0002D0, "Member 'WBP_MapMarker_Win_C_ExecuteUbergraph_WBP_MapMarker_Win::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(WBP_MapMarker_Win_C_ExecuteUbergraph_WBP_MapMarker_Win, CallFunc_GetIconType_ReturnValue) == 0x0002D4, "Member 'WBP_MapMarker_Win_C_ExecuteUbergraph_WBP_MapMarker_Win::CallFunc_GetIconType_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_MapMarker_Win_C_ExecuteUbergraph_WBP_MapMarker_Win, CallFunc_Array_Get_Item_6) == 0x0002D8, "Member 'WBP_MapMarker_Win_C_ExecuteUbergraph_WBP_MapMarker_Win::CallFunc_Array_Get_Item_6' has a wrong offset!");
static_assert(offsetof(WBP_MapMarker_Win_C_ExecuteUbergraph_WBP_MapMarker_Win, CallFunc_Array_Length_ReturnValue_1) == 0x0002E0, "Member 'WBP_MapMarker_Win_C_ExecuteUbergraph_WBP_MapMarker_Win::CallFunc_Array_Length_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_MapMarker_Win_C_ExecuteUbergraph_WBP_MapMarker_Win, CallFunc_Less_IntInt_ReturnValue_1) == 0x0002E4, "Member 'WBP_MapMarker_Win_C_ExecuteUbergraph_WBP_MapMarker_Win::CallFunc_Less_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_MapMarker_Win_C_ExecuteUbergraph_WBP_MapMarker_Win, K2Node_MakeArray_Array_2) == 0x0002E8, "Member 'WBP_MapMarker_Win_C_ExecuteUbergraph_WBP_MapMarker_Win::K2Node_MakeArray_Array_2' has a wrong offset!");

// Function WBP_MapMarker_Win.WBP_MapMarker_Win_C.OnRemovedFromFocusPath
// 0x0008 (0x0008 - 0x0000)
struct WBP_MapMarker_Win_C_OnRemovedFromFocusPath final
{
public:
	struct FFocusEvent                            InFocusEvent;                                      // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
};
static_assert(alignof(WBP_MapMarker_Win_C_OnRemovedFromFocusPath) == 0x000004, "Wrong alignment on WBP_MapMarker_Win_C_OnRemovedFromFocusPath");
static_assert(sizeof(WBP_MapMarker_Win_C_OnRemovedFromFocusPath) == 0x000008, "Wrong size on WBP_MapMarker_Win_C_OnRemovedFromFocusPath");
static_assert(offsetof(WBP_MapMarker_Win_C_OnRemovedFromFocusPath, InFocusEvent) == 0x000000, "Member 'WBP_MapMarker_Win_C_OnRemovedFromFocusPath::InFocusEvent' has a wrong offset!");

// Function WBP_MapMarker_Win.WBP_MapMarker_Win_C.RemoveCustomIcon__DelegateSignature
// 0x0008 (0x0008 - 0x0000)
struct WBP_MapMarker_Win_C_RemoveCustomIcon__DelegateSignature final
{
public:
	class UWBP_Map_IconCustom_C*                  Icon;                                              // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_MapMarker_Win_C_RemoveCustomIcon__DelegateSignature) == 0x000008, "Wrong alignment on WBP_MapMarker_Win_C_RemoveCustomIcon__DelegateSignature");
static_assert(sizeof(WBP_MapMarker_Win_C_RemoveCustomIcon__DelegateSignature) == 0x000008, "Wrong size on WBP_MapMarker_Win_C_RemoveCustomIcon__DelegateSignature");
static_assert(offsetof(WBP_MapMarker_Win_C_RemoveCustomIcon__DelegateSignature, Icon) == 0x000000, "Member 'WBP_MapMarker_Win_C_RemoveCustomIcon__DelegateSignature::Icon' has a wrong offset!");

// Function WBP_MapMarker_Win.WBP_MapMarker_Win_C.SetEdittingIcon
// 0x0008 (0x0008 - 0x0000)
struct WBP_MapMarker_Win_C_SetEdittingIcon final
{
public:
	class UWBP_Map_IconCustom_C*                  CustomIcon;                                        // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_MapMarker_Win_C_SetEdittingIcon) == 0x000008, "Wrong alignment on WBP_MapMarker_Win_C_SetEdittingIcon");
static_assert(sizeof(WBP_MapMarker_Win_C_SetEdittingIcon) == 0x000008, "Wrong size on WBP_MapMarker_Win_C_SetEdittingIcon");
static_assert(offsetof(WBP_MapMarker_Win_C_SetEdittingIcon, CustomIcon) == 0x000000, "Member 'WBP_MapMarker_Win_C_SetEdittingIcon::CustomIcon' has a wrong offset!");

}

