#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_AssignBoard_PalSlotButton

#include "Basic.hpp"

#include "Pal_structs.hpp"
#include "WBP_PalCharacterSlotButtonBase_classes.hpp"
#include "Engine_structs.hpp"
#include "UMG_structs.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_AssignBoard_PalSlotButton.WBP_AssignBoard_PalSlotButton_C
// 0x0018 (0x04D0 - 0x04B8)
class UWBP_AssignBoard_PalSlotButton_C final : public UWBP_PalCharacterSlotButtonBase_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_WBP_AssignBoard_PalSlotButton_C;    // 0x04B8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWBP_AssignBoard_PalSlot_C*             WBP_AssignBoard_PalSlot;                           // 0x04C0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_PalInvisibleButton_C*              WBP_PalInvisibleButton;                            // 0x04C8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void BndEvt__WBP_AssignBoard_PalSlotButton_WBP_PalInvisibleButton_K2Node_ComponentBoundEvent_1_CommonButtonBaseClicked__DelegateSignature(class UCommonButtonBase* Button);
	void BndEvt__WBP_AssignBoard_PalSlotButton_WBP_PalInvisibleButton_K2Node_ComponentBoundEvent_2_CommonButtonBaseClicked__DelegateSignature(class UCommonButtonBase* Button);
	void ExecuteUbergraph_WBP_AssignBoard_PalSlotButton(int32 EntryPoint);
	void OnInitialized();
	void RegisterButton(class UCommonButtonBase** Button);
	void RegisterCharacterSlotWidget(class UWBP_PalCharacterSlotBase_C** CharacterSlotWidget);
	void Set_Is_Fixed_Assign(bool IsAssign);
	void SetDisplayGender(bool IsDisplay);
	void SetReferenceWorkId(const struct FGuid& WorkId);
	void SetReferenceWorkSuitability(TArray<EPalWorkSuitability>& Suitabilities);
	void SetSelectedCheck(bool IsCheck);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_AssignBoard_PalSlotButton_C">();
	}
	static class UWBP_AssignBoard_PalSlotButton_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_AssignBoard_PalSlotButton_C>();
	}
};
static_assert(alignof(UWBP_AssignBoard_PalSlotButton_C) == 0x000008, "Wrong alignment on UWBP_AssignBoard_PalSlotButton_C");
static_assert(sizeof(UWBP_AssignBoard_PalSlotButton_C) == 0x0004D0, "Wrong size on UWBP_AssignBoard_PalSlotButton_C");
static_assert(offsetof(UWBP_AssignBoard_PalSlotButton_C, UberGraphFrame_WBP_AssignBoard_PalSlotButton_C) == 0x0004B8, "Member 'UWBP_AssignBoard_PalSlotButton_C::UberGraphFrame_WBP_AssignBoard_PalSlotButton_C' has a wrong offset!");
static_assert(offsetof(UWBP_AssignBoard_PalSlotButton_C, WBP_AssignBoard_PalSlot) == 0x0004C0, "Member 'UWBP_AssignBoard_PalSlotButton_C::WBP_AssignBoard_PalSlot' has a wrong offset!");
static_assert(offsetof(UWBP_AssignBoard_PalSlotButton_C, WBP_PalInvisibleButton) == 0x0004C8, "Member 'UWBP_AssignBoard_PalSlotButton_C::WBP_PalInvisibleButton' has a wrong offset!");

}

