#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_IngameMenu_WorkSpace_Slider

#include "Basic.hpp"


namespace SDK::Params
{

// Function WBP_IngameMenu_WorkSpace_Slider.WBP_IngameMenu_WorkSpace_Slider_C.BndEvt__WBP_IngameMenu_WorkSpace_Slider_Slider_K2Node_ComponentBoundEvent_1_OnFloatValueChangedEvent__DelegateSignature
// 0x0004 (0x0004 - 0x0000)
struct WBP_IngameMenu_WorkSpace_Slider_C_BndEvt__WBP_IngameMenu_WorkSpace_Slider_Slider_K2Node_ComponentBoundEvent_1_OnFloatValueChangedEvent__DelegateSignature final
{
public:
	float                                         Value;                                             // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_IngameMenu_WorkSpace_Slider_C_BndEvt__WBP_IngameMenu_WorkSpace_Slider_Slider_K2Node_ComponentBoundEvent_1_OnFloatValueChangedEvent__DelegateSignature) == 0x000004, "Wrong alignment on WBP_IngameMenu_WorkSpace_Slider_C_BndEvt__WBP_IngameMenu_WorkSpace_Slider_Slider_K2Node_ComponentBoundEvent_1_OnFloatValueChangedEvent__DelegateSignature");
static_assert(sizeof(WBP_IngameMenu_WorkSpace_Slider_C_BndEvt__WBP_IngameMenu_WorkSpace_Slider_Slider_K2Node_ComponentBoundEvent_1_OnFloatValueChangedEvent__DelegateSignature) == 0x000004, "Wrong size on WBP_IngameMenu_WorkSpace_Slider_C_BndEvt__WBP_IngameMenu_WorkSpace_Slider_Slider_K2Node_ComponentBoundEvent_1_OnFloatValueChangedEvent__DelegateSignature");
static_assert(offsetof(WBP_IngameMenu_WorkSpace_Slider_C_BndEvt__WBP_IngameMenu_WorkSpace_Slider_Slider_K2Node_ComponentBoundEvent_1_OnFloatValueChangedEvent__DelegateSignature, Value) == 0x000000, "Member 'WBP_IngameMenu_WorkSpace_Slider_C_BndEvt__WBP_IngameMenu_WorkSpace_Slider_Slider_K2Node_ComponentBoundEvent_1_OnFloatValueChangedEvent__DelegateSignature::Value' has a wrong offset!");

// Function WBP_IngameMenu_WorkSpace_Slider.WBP_IngameMenu_WorkSpace_Slider_C.ExecuteUbergraph_WBP_IngameMenu_WorkSpace_Slider
// 0x0068 (0x0068 - 0x0000)
struct WBP_IngameMenu_WorkSpace_Slider_C_ExecuteUbergraph_WBP_IngameMenu_WorkSpace_Slider final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         K2Node_CustomEvent_Min;                            // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         K2Node_CustomEvent_Max;                            // 0x0008(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Conv_IntToFloat_ReturnValue;              // 0x000C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FText                                   CallFunc_Conv_IntToText_ReturnValue;               // 0x0010(0x0018)()
	float                                         CallFunc_Conv_IntToFloat_ReturnValue_1;            // 0x0028(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_5C04[0x4];                                     // 0x002C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   CallFunc_Conv_IntToText_ReturnValue_1;             // 0x0030(0x0018)()
	int32                                         K2Node_CustomEvent_Current;                        // 0x0048(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Conv_IntToFloat_ReturnValue_2;            // 0x004C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         K2Node_ComponentBoundEvent_Value;                  // 0x0050(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Round_ReturnValue;                        // 0x0054(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_NotEqual_IntInt_ReturnValue;              // 0x0058(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_5C05[0x7];                                     // 0x0059(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_Round_A_ImplicitCast;                     // 0x0060(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_IngameMenu_WorkSpace_Slider_C_ExecuteUbergraph_WBP_IngameMenu_WorkSpace_Slider) == 0x000008, "Wrong alignment on WBP_IngameMenu_WorkSpace_Slider_C_ExecuteUbergraph_WBP_IngameMenu_WorkSpace_Slider");
static_assert(sizeof(WBP_IngameMenu_WorkSpace_Slider_C_ExecuteUbergraph_WBP_IngameMenu_WorkSpace_Slider) == 0x000068, "Wrong size on WBP_IngameMenu_WorkSpace_Slider_C_ExecuteUbergraph_WBP_IngameMenu_WorkSpace_Slider");
static_assert(offsetof(WBP_IngameMenu_WorkSpace_Slider_C_ExecuteUbergraph_WBP_IngameMenu_WorkSpace_Slider, EntryPoint) == 0x000000, "Member 'WBP_IngameMenu_WorkSpace_Slider_C_ExecuteUbergraph_WBP_IngameMenu_WorkSpace_Slider::EntryPoint' has a wrong offset!");
static_assert(offsetof(WBP_IngameMenu_WorkSpace_Slider_C_ExecuteUbergraph_WBP_IngameMenu_WorkSpace_Slider, K2Node_CustomEvent_Min) == 0x000004, "Member 'WBP_IngameMenu_WorkSpace_Slider_C_ExecuteUbergraph_WBP_IngameMenu_WorkSpace_Slider::K2Node_CustomEvent_Min' has a wrong offset!");
static_assert(offsetof(WBP_IngameMenu_WorkSpace_Slider_C_ExecuteUbergraph_WBP_IngameMenu_WorkSpace_Slider, K2Node_CustomEvent_Max) == 0x000008, "Member 'WBP_IngameMenu_WorkSpace_Slider_C_ExecuteUbergraph_WBP_IngameMenu_WorkSpace_Slider::K2Node_CustomEvent_Max' has a wrong offset!");
static_assert(offsetof(WBP_IngameMenu_WorkSpace_Slider_C_ExecuteUbergraph_WBP_IngameMenu_WorkSpace_Slider, CallFunc_Conv_IntToFloat_ReturnValue) == 0x00000C, "Member 'WBP_IngameMenu_WorkSpace_Slider_C_ExecuteUbergraph_WBP_IngameMenu_WorkSpace_Slider::CallFunc_Conv_IntToFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_IngameMenu_WorkSpace_Slider_C_ExecuteUbergraph_WBP_IngameMenu_WorkSpace_Slider, CallFunc_Conv_IntToText_ReturnValue) == 0x000010, "Member 'WBP_IngameMenu_WorkSpace_Slider_C_ExecuteUbergraph_WBP_IngameMenu_WorkSpace_Slider::CallFunc_Conv_IntToText_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_IngameMenu_WorkSpace_Slider_C_ExecuteUbergraph_WBP_IngameMenu_WorkSpace_Slider, CallFunc_Conv_IntToFloat_ReturnValue_1) == 0x000028, "Member 'WBP_IngameMenu_WorkSpace_Slider_C_ExecuteUbergraph_WBP_IngameMenu_WorkSpace_Slider::CallFunc_Conv_IntToFloat_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_IngameMenu_WorkSpace_Slider_C_ExecuteUbergraph_WBP_IngameMenu_WorkSpace_Slider, CallFunc_Conv_IntToText_ReturnValue_1) == 0x000030, "Member 'WBP_IngameMenu_WorkSpace_Slider_C_ExecuteUbergraph_WBP_IngameMenu_WorkSpace_Slider::CallFunc_Conv_IntToText_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_IngameMenu_WorkSpace_Slider_C_ExecuteUbergraph_WBP_IngameMenu_WorkSpace_Slider, K2Node_CustomEvent_Current) == 0x000048, "Member 'WBP_IngameMenu_WorkSpace_Slider_C_ExecuteUbergraph_WBP_IngameMenu_WorkSpace_Slider::K2Node_CustomEvent_Current' has a wrong offset!");
static_assert(offsetof(WBP_IngameMenu_WorkSpace_Slider_C_ExecuteUbergraph_WBP_IngameMenu_WorkSpace_Slider, CallFunc_Conv_IntToFloat_ReturnValue_2) == 0x00004C, "Member 'WBP_IngameMenu_WorkSpace_Slider_C_ExecuteUbergraph_WBP_IngameMenu_WorkSpace_Slider::CallFunc_Conv_IntToFloat_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(WBP_IngameMenu_WorkSpace_Slider_C_ExecuteUbergraph_WBP_IngameMenu_WorkSpace_Slider, K2Node_ComponentBoundEvent_Value) == 0x000050, "Member 'WBP_IngameMenu_WorkSpace_Slider_C_ExecuteUbergraph_WBP_IngameMenu_WorkSpace_Slider::K2Node_ComponentBoundEvent_Value' has a wrong offset!");
static_assert(offsetof(WBP_IngameMenu_WorkSpace_Slider_C_ExecuteUbergraph_WBP_IngameMenu_WorkSpace_Slider, CallFunc_Round_ReturnValue) == 0x000054, "Member 'WBP_IngameMenu_WorkSpace_Slider_C_ExecuteUbergraph_WBP_IngameMenu_WorkSpace_Slider::CallFunc_Round_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_IngameMenu_WorkSpace_Slider_C_ExecuteUbergraph_WBP_IngameMenu_WorkSpace_Slider, CallFunc_NotEqual_IntInt_ReturnValue) == 0x000058, "Member 'WBP_IngameMenu_WorkSpace_Slider_C_ExecuteUbergraph_WBP_IngameMenu_WorkSpace_Slider::CallFunc_NotEqual_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_IngameMenu_WorkSpace_Slider_C_ExecuteUbergraph_WBP_IngameMenu_WorkSpace_Slider, CallFunc_Round_A_ImplicitCast) == 0x000060, "Member 'WBP_IngameMenu_WorkSpace_Slider_C_ExecuteUbergraph_WBP_IngameMenu_WorkSpace_Slider::CallFunc_Round_A_ImplicitCast' has a wrong offset!");

// Function WBP_IngameMenu_WorkSpace_Slider.WBP_IngameMenu_WorkSpace_Slider_C.GetPercent
// 0x0008 (0x0008 - 0x0000)
struct WBP_IngameMenu_WorkSpace_Slider_C_GetPercent final
{
public:
	float                                         ReturnValue;                                       // 0x0000(0x0004)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_GetNormalizedValue_ReturnValue;           // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_IngameMenu_WorkSpace_Slider_C_GetPercent) == 0x000004, "Wrong alignment on WBP_IngameMenu_WorkSpace_Slider_C_GetPercent");
static_assert(sizeof(WBP_IngameMenu_WorkSpace_Slider_C_GetPercent) == 0x000008, "Wrong size on WBP_IngameMenu_WorkSpace_Slider_C_GetPercent");
static_assert(offsetof(WBP_IngameMenu_WorkSpace_Slider_C_GetPercent, ReturnValue) == 0x000000, "Member 'WBP_IngameMenu_WorkSpace_Slider_C_GetPercent::ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_IngameMenu_WorkSpace_Slider_C_GetPercent, CallFunc_GetNormalizedValue_ReturnValue) == 0x000004, "Member 'WBP_IngameMenu_WorkSpace_Slider_C_GetPercent::CallFunc_GetNormalizedValue_ReturnValue' has a wrong offset!");

// Function WBP_IngameMenu_WorkSpace_Slider.WBP_IngameMenu_WorkSpace_Slider_C.OnValueChanged__DelegateSignature
// 0x0004 (0x0004 - 0x0000)
struct WBP_IngameMenu_WorkSpace_Slider_C_OnValueChanged__DelegateSignature final
{
public:
	int32                                         NewCount;                                          // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_IngameMenu_WorkSpace_Slider_C_OnValueChanged__DelegateSignature) == 0x000004, "Wrong alignment on WBP_IngameMenu_WorkSpace_Slider_C_OnValueChanged__DelegateSignature");
static_assert(sizeof(WBP_IngameMenu_WorkSpace_Slider_C_OnValueChanged__DelegateSignature) == 0x000004, "Wrong size on WBP_IngameMenu_WorkSpace_Slider_C_OnValueChanged__DelegateSignature");
static_assert(offsetof(WBP_IngameMenu_WorkSpace_Slider_C_OnValueChanged__DelegateSignature, NewCount) == 0x000000, "Member 'WBP_IngameMenu_WorkSpace_Slider_C_OnValueChanged__DelegateSignature::NewCount' has a wrong offset!");

// Function WBP_IngameMenu_WorkSpace_Slider.WBP_IngameMenu_WorkSpace_Slider_C.SetCurrentValue
// 0x0004 (0x0004 - 0x0000)
struct WBP_IngameMenu_WorkSpace_Slider_C_SetCurrentValue final
{
public:
	int32                                         Param_Current;                                     // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_IngameMenu_WorkSpace_Slider_C_SetCurrentValue) == 0x000004, "Wrong alignment on WBP_IngameMenu_WorkSpace_Slider_C_SetCurrentValue");
static_assert(sizeof(WBP_IngameMenu_WorkSpace_Slider_C_SetCurrentValue) == 0x000004, "Wrong size on WBP_IngameMenu_WorkSpace_Slider_C_SetCurrentValue");
static_assert(offsetof(WBP_IngameMenu_WorkSpace_Slider_C_SetCurrentValue, Param_Current) == 0x000000, "Member 'WBP_IngameMenu_WorkSpace_Slider_C_SetCurrentValue::Param_Current' has a wrong offset!");

// Function WBP_IngameMenu_WorkSpace_Slider.WBP_IngameMenu_WorkSpace_Slider_C.SetupRange
// 0x0008 (0x0008 - 0x0000)
struct WBP_IngameMenu_WorkSpace_Slider_C_SetupRange final
{
public:
	int32                                         Min;                                               // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Max;                                               // 0x0004(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_IngameMenu_WorkSpace_Slider_C_SetupRange) == 0x000004, "Wrong alignment on WBP_IngameMenu_WorkSpace_Slider_C_SetupRange");
static_assert(sizeof(WBP_IngameMenu_WorkSpace_Slider_C_SetupRange) == 0x000008, "Wrong size on WBP_IngameMenu_WorkSpace_Slider_C_SetupRange");
static_assert(offsetof(WBP_IngameMenu_WorkSpace_Slider_C_SetupRange, Min) == 0x000000, "Member 'WBP_IngameMenu_WorkSpace_Slider_C_SetupRange::Min' has a wrong offset!");
static_assert(offsetof(WBP_IngameMenu_WorkSpace_Slider_C_SetupRange, Max) == 0x000004, "Member 'WBP_IngameMenu_WorkSpace_Slider_C_SetupRange::Max' has a wrong offset!");

}

